const yoKaiList = [
    { name: "Woko", img: "alcaldero.png" },
    { name: "Pagno", img: "sinna.png" },
    { name: "Alfoncéo", img: "sinnareno.png" },
    { name: "Toumou", img: "katano.png" },
    { name: "Lamlam'mou", img: "katananai.png" },
    { name: "Samoumouraï", img: "katakroken.png" },
    { name: "Sumochi", img: "mochimacho.png" },
    { name: "Mochimacho", img: "machimio.png" },
    { name: "Heaumer", img: "yelmandante.png" },
    { name: "Bushidos", img: "juntollero.png" },
    { name: "Âmiral", img: "genedaver.png" },
    { name: "Feulion", img: "flamileon.png" },
    { name: "Vibrilion", img: "tembloleon.png" },
    { name: "Siro", img: "sirleon.png" },
    { name: "Bonneto", img: "ludorai.png" },
    { name: "Sabri", img: "lustre.png" },
    { name: "Padelou", img: "Furtre.png" },
    { name: "Orox", img: "dortre.png" },
    { name: "Benkei", img: "benkei.png" },
    { name: "B3-NK1", img: "b3-nk1.png" },
    { name: "Sushiyama", img: "sushiyama.png" },
    { name: "Kapunki", img: "kapunki.png" },
    { name: "Scatcheur", img: "lucharabajo.png" },
    { name: "Scarmouche", img: "camperabajo.png" },
    { name: "Scarnage", img: "chafarabajo.png" },
    { name: "Zerberker", img: "osfurio.png" },
    { name: "Fouétar", img: "sacoco.png" },
    { name: "Morvobec", img: "mokopavo.png" },
    { name: "Matchou", img: "pachus.png" },
    { name: "Chaipô", img: "komemo.png" },
    { name: "Gagalurin", img: "tontolin.png" },
    { name: "Papa Ress", img: "yopaso.png" },
    { name: "Ralbouc", img: "puf.png" },
    { name: "Bastata", img: "yanomas.png" },
    { name: "Marra", img: "algazara.png" },
    { name: "Violette", img: "labizula.png" },
    { name: "Toutouïe", img: "cotilleja.png" },
    { name: "Babalance", img: "marulleja.png" },
    { name: "Mémétal", img: "esquelleja.png" },
    { name: "Cupistol", img: "cupistolo.png" },
    { name: "Donjouant", img: "casanovo.png" },
    { name: "Nonjouan", img: "casanono.png" },
    { name: "Padrézo", img: "ondivoro.png" },
    { name: "Emettor", img: "coberturo.png" },
    { name: "Dynamo", img: "estatinarca.png" },
    { name: "Télémir", img: "telespejo.png" },
    { name: "Nuiroir", img: "malpejismo.png" },
    { name: "Hiblusion", img: "iluho.png" },
    { name: "Hibrouille", img: "eluho.png" },
    { name: "Hibourling", img: "ubiuho.png" },
    { name: "Espi", img: "trilepata.png" },
    { name: "Etassivilia", img: "tetrariosa.png" },
    { name: "Tengu", img: "tengu.png" },
    { name: "Tengurou", img: "flamngu.png" },
    { name: "Kyubi", img: "kyubi.png" },
{ name: "Barakabo", img: "nievacolas.png" },
{ name: "Darabajoie", img: "tentelento.png" },
{ name: "Darumastar", img: "tentemacho.png" },
{ name: "Goruma", img: "tenterila.png" },
{ name: "Nanpart", img: "nihablar.png" },
{ name: "Passpa", img: "impas.png" },
{ name: "Granpart", img: "murallin.png" },
{ name: "Hauber", img: "lorigon.png" },
{ name: "Pachycoul", img: "inquielifante.png" },
{ name: "Persévéfant", img: "perselefante.png" },
{ name: "Boulapic", img: "globqueo.png" },
{ name: "Bouldacier", img: "globtundente.png" },
{ name: "Lama Laya", img: "montaña_loca.png" },
{ name: "Etna Magma", img: "lord_lava.png" },
{ name: "Loubarbare", img: "rebelcebu.png" },
{ name: "Racaîd", img: "caporrista.png" },
{ name: "Frérosse", img: "hermanion.png" },
{ name: "Coléroptère", img: "pegarabajo.png" },
{ name: "Rhinolimit", img: "enormarabajo.png" },
{ name: "Corniaque", img: "cuernarabajo.png" },
{ name: "Castelius III", img: "castelius_III.png" },
{ name: "Castelius II", img: "castelius_II.png" },
{ name: "Castelius I", img: "Castelius_I.png" },
{ name: "Castelius Max", img: "Maxicastelius.png" },
{ name: "Robonyan", img: "robonyan.png" },
{ name: "Oronyan", img: "aureonyan.png" },
{ name: "Misterre", img: "pom.png" },
{ name: "Ressak", img: "flus.png" },
    { name: "Squarlett", img: "deslumbrella.png" },
    { name: "Margoth", img: "rechinella.png" },
    { name: "Squelèbelle", img: "esquelebella.png" },
    { name: "Cigalopin", img: "ningarra.png" },
    { name: "Cigaillard", img: "habilgarra.png" },
    { name: "Cigazouille", img: "cantigarra.png" },
    { name: "Chihuaglagla", img: "escanlofrio.png" },
    { name: "Froahuahua", img: "frihuahua.png" },
    { name: "Cho-cho", img: "lavadenco.png" },
    { name: "Jibanyan", img: "jibanyan.png" },
    { name: "Epinyan", img: "espinyan.png" },
    { name: "Bandinyan", img: "pelochnyan.png" },
    { name: "Kappacap", img: "kappandante.png" },
    { name: "Appak", img: "kappadachin.png" },
    { name: "Kappaloha", img: "kapparfista.png" },
    { name: "Komasan", img: "komasan.png" },
    { name: "Komaous", img: "komaleon.png" },
    { name: "Komajiro", img: "komajiro.png" },
    { name: "Komistigri", img: "komatigrado.png" },
    { name: "Baku", img: "baku.png" },
    { name: "Tapur", img: "blanpir.png" },
    { name: "Pitou", img: "pufipatitas.png" },
    { name: "Choubidou", img: "pufilindo.png" },
    { name: "Satandre", img: "pufimaloso.png" },
    { name: "Angélik", img: "fristina.png" },
    { name: "Blizzaria", img: "granizia.png" },
    { name: "Damona", img: "damona.png" },
{ name: "Noripop", img: "cimbron.png" },
{ name: "Wakapoeira", img: "pasodon.png" },
{ name: "Salsalga", img: "ritma.png" },
{ name: "Amoiz", img: "kieroto.png" },
{ name: "Pikor", img: "zampo.png" },
{ name: "Granpapéti", img: "abuzampa.png" },
{ name: "Puissanfon", img: "gargazampa.png" },
{ name: "Grainpère", img: "aburroz.png" },
{ name: "Nomoné", img: "nomeda.png" },
{ name: "Noproblemo", img: "opti.png" },
{ name: "Papiltation", img: "enerposa.png" },
{ name: "Papiltension", img: "eneposa.png" },
{ name: "Hyprapillon", img: "mejorposa.png" },
{ name: "Vitapillon", img: "vivariposa.png" },
{ name: "Jojojoyeux", img: "felisonte.png" },
{ name: "Paradoxa", img: "reversa.png" },
{ name: "Potaumorose", img: "reversada.png" },
{ name: "Ratatam", img: "tricotom.png" },
{ name: "Supernoël", img: "dadivo.png" },
{ name: "Dédé", img: "bolilete.png" },
{ name: "Dédéstin", img: "doblilete.png" },
{ name: "Tontonerre", img: "papa_rayo.png" },
{ name: "Omnitonton", img: "tio_infinito.png" },
{ name: "Tata Aura", img: "mama_aura.png" },
{ name: "Tata Câlin", img: "tita_corazon.png" },
{ name: "Égaroni", img: "noguio.png" },
{ name: "Onisoi", img: "topami.png" },
{ name: "Tortico", img: "algio.png" },
{ name: "Tendino", img: "agujeto.png" },
{ name: "Contracto", img: "machaka.png" },
{ name: "Nihilistik", img: "negatisquito.png" },
{ name: "Émousstik", img: "deprisquito.png" },
{ name: "Grattoptère", img: "picorron.png" },
{ name: "Marcognito", img: "nomeven.png" },
{ name: "Ninjamévu", img: "nostoy.png" },
{ name: "Nihilo", img: "nul_.png" },
{ name: "Chauvekipeut", img: "encielago.png" },
{ name: "Chauv'coucou", img: "caserielago.png" },
{ name: "Vampiloc", img: "ermicielago.png" },
{ name: "Suspicioni", img: "suspicioni.png" },
{ name: "Ragioni", img: "pataletoni.png" },
{ name: "Contrarioni", img: "contrarioni.png" },
{ name: "Tengubre", img: "tengulecto.png" },
{ name: "Bibliotengu", img: "tengullon.png" },
{ name: "Nimpégase", img: "negasus.png" },
{ name: "Hennimi", img: "pifiasus.png" },
{ name: "Timidémon", img: "timidiablo.png" },
{ name: "Belzel", img: "osademonio.png" },
{ name: "Dente", img: "conde_caries.png" },
{ name: "Vénaldo", img: "avarqueroso.png" },
{ name: "Maltesse", img: "diables.png" },
{ name: "Malmidal", img: "ejemtos.png" },
{ name: "Écchinose", img: "erizlor.png" },
{ name: "Chiperpiou", img: "cartepollo.png" },
{ name: "Pioubidou", img: "rafaz.png" },
{ name: "Flamente", img: "ayay.png" },
{ name: "Volibrius", img: "horterraro.png" },
{ name: "Volatriste", img: "alarcion.png" },
{ name: "Corniot", img: "cantonio.png" },
{ name: "Bicorniot", img: "multiniche.png" },
{ name: "Cerbébert", img: "ser_bero.png" },
{ name: "Humidon", img: "goto.png" },
{ name: "Délujien", img: "sirimiri.png" },
{ name: "Fryzeur", img: "copo.png" },
{ name: "Kongel", img: "ventisquero.png" },
{ name: "Hémorhino", img: "coagulon.png" },
{ name: "Blablara", img: "reboca.png" },
{ name: "Umilie", img: "pilicajosa.png" },
{ name: "Lulugubre", img: "negatalia.png" },
{ name: "Pégaz", img: "cuesco.png" },
{ name: "Méphito", img: "peditum.png" },
{ name: "Misterbide", img: "graciosno.png" },
{ name: "Flopito", img: "hilarion.png" },
{ name: "Cenridion", img: "arruñona.png" },
{ name: "Jouvencia", img: "belladona.png" },
{ name: "Éterna", img: "eterna.png" },
{ name: "Insomnelle", img: "insomna.png" },
{ name: "Morféa", img: "morfea.png" },
{ name: "Noko", img: "noko.png" },
{ name: "Nénunoko", img: "florinoko.png" },
{ name: "Pandanoko", img: "pandanoko.png" },
{ name: "Anghihihille", img: "anjijila.png" },
{ name: "Méroubadour", img: "tenongrio.png" },
{ name: "Urnaconda", img: "urnaconda.png" },
{ name: "Murhaine", img: "pezqueroso.png" },
{ name: "Saumhonni", img: "pezgativo.png" },
{ name: "Vexturgeon", img: "pezquiciado.png" },
{ name: "Dracounet", img: "draqui.png" },
{ name: "Sire Dragon", img: "lord_dragon.png" },
{ name: "Drago", img: "dragon_azur.png" },
{ name: "Bababou", img: "ido.png" },
{ name: "Tourneboul", img: "turdido.png" },
{ name: "Croquin", img: "pelluron.png" },
{ name: "Inisquale", img: "pringuron.png" },
{ name: "Claquille", img: "boquirroto.png" },
{ name: "Cocpille", img: "yopago.png" },
{ name: "Jacquasseur", img: "charlaton.png" },
{ name: "Bananar", img: "tochaplatano.png" },
{ name: "Vipètesec", img: "mandicoro.png" },
{ name: "Vipérale", img: "ciniserpe.png" },
{ name: "Vipairflay", img: "arfidio.png" },
{ name: "Octorgone", img: "venocto.png" },
{ name: "Octorgombre", img: "venoctoscuro.png" },
{ name: "Shogunyan", img: "shogunyan.png" },
{ name: "Komashura", img: "komasura.png" },
{ name: "Cabotin", img: "dandiniche.png" },
{ name: "Camaieul", img: "abuflorido.png" },
{ name: "Gorgouille", img: "dorantuo.png" },
{ name: "Saphinyan", img: "zafinyan.png" },
{ name: "Émeranyan", img: "esmenyan.png" },
{ name: "Rubinyan", img: "rubinyan.png" },
{ name: "Topanyan", img: "topanyan.png" },
{ name: "Diamanyan", img: "diamanyan.png" },
{ name: "Triptyk", img: "babamandra.png" },
{ name: "Crocho", img: "termascino.png" },
{ name: "Carpitaine", img: "bergantin.png" },
{ name: "Ombraptor", img: "animanstruo.png" },
{ name: "Sabroclair", img: "fantasmurai.png" },
{ name: "Inamygal", img: "tarantutor.png" },
{ name: "Dr Jobard", img: "dr._majarov.png" },
{ name: "McKraken", img: "mckraken.png" },
{ name: "McKraken", img: "mckraken_2.png" },
{ name: "Volteface", img: "duoleta.png" },
{ name: "Didgeai", img: "cantaderna.png" },
{ name: "Hydreux", img: "ojimandra.png" },
{ name: "Porcinator", img: "jabalupo.png" },
{ name: "Styx VI", img: "estigio_vi.png" },
{ name: "Nébulor", img: "clipso.png" },
{ name: "Pr Létripe", img: "dr._sintripas.png" },
{ name: "Hagacurée", img: "terrormadura.png" },
{ name: "Rancornet", img: "calarrupto.png" },
{ name: "Potofeu", img: "caldewok.png" },
{ name: "Gargaros", img: "gargantuo.png" },
{ name: "Ogralos", img: "cazamentires.png" },
{ name: "Orqanos", img: "demoniorco.png" },
 { name: "Samoussrai", img: "Milimpiano.png" },            
    { name: "Ronimpec", img: "Samulimpio.png" },
    { name: "Roupilion", img: "Dormileon.png" },
    { name: "Rugis", img: "Leon_Alfa.png" },
    { name: "Trépigno", img: "Pataleto.png" },
    { name: "Sale de bain", img: "Chupatinas.png" },
    { name: "Agonigiri", img: "Cortarroz.png" },
    { name: "Onigirix", img: "Socarrat.png" },
    { name: "Bouh", img: "Atierrador.png" },
    { name: "Coach Antonic", img: "Capi-Cachas.png" },
    { name: "Démophage", img: "Devoramonios.png" },
    { name: "Vampéric", img: "Devoralmas.png" },
    { name: "Pleurapluie", img: "Fracaguas.png" },
    { name: "Gastong", img: "Chancleto.png" },
    { name: "Mémogre", img: "Komecasa.png" },
    { name: "Ovide", img: "Sincara.png" },
    { name: "Trodésolé", img: "Losiento.png" },
    { name: "Pardomino", img: "Domiplof.png" },
    { name: "Brumette", img: "Niebli.png" },
    { name: "Brumella", img: "Nebula.png" },
    { name: "Maître Oden", img: "Don_Kaldo.png" },
    { name: "Mythovni", img: "Falsillo.png" },
    { name: "Apélicain", img: "Apelicano.png" },
    { name: "Triptic-tac", img: "Trielespejo.png" },
    { name: "Valentino", img: "Ambrosio.png" },
    { name: "Chymère", img: "Kimera.png" },
    { name: "Chyper", img: "Kimerreal.png" },
    { name: "Potache", img: "Aterracota.png" },
    { name: "Jalouseriz", img: "Quierodeso.png" },
    { name: "Fanfanfaron", img: "Gambulloso.png" },
    { name: "Égare-dare", img: "Indiligencio.png" },
    { name: "Charivari", img: "Tanquivocado.png" },
    { name: "Humainequin", img: "Mimoniqui.png" },
    { name: "Pachypipi", img: "Mamuguanto.png" },
    { name: "Antonnerre", img: "Rayael.png" },
    { name: "Parantonn", img: "Cazarayos.png" },
    { name: "Suinthan", img: "Zudado.png" },
    { name: "Crapop", img: "Eleganfibio.png" },
    { name: "Geeko", img: "Frikigarto.png" },
    { name: "Gambeth", img: "Patis.png" },
    { name: "Traviolette", img: "Picassina.png" },
    { name: "Yokoeil", img: "Chiclope.png" },
    { name: "Buchinyan", img: "Buchinyan.png" },
    { name: "Bakuku", img: "Somnia.png" },
    { name: "Sabruine", img: "Cellisca.png" },
    { name: "Vito", img: "Rapidizo.png" },
    { name: "Timours", img: "Oso_Boco.png" },
    { name: "Faux Kappa", img: "Kappafalso.png" },
    { name: "Kappadissi", img: "Tigrappa.png" },
    { name: "Maître Nyada", img: "Gran_Mangu.png" },
    { name: "Algacarena", img: "Algacabana.png" },
    { name: "Papilla", img: "Niscala.png" },
    { name: "Mme Papilla", aliases: ["Mme Papilla", "Madamme Papilla"], img: "Curaniscala.png" },
    { name: "Felipaix", img: "Arenito.png" },
    { name: "M. Felipaix", aliases: ["M. Felipaix", "M Felipaix", "Monsieur Felipaix"], img: "Don_Arenito.png" },
    { name: "Parasolal", img: "Sombrillo.png" },
    { name: "Scarasol", img: "Sombrillogro.png" },
    { name: "Ivanupieds", img: "Pauperman.png" },
    { name: "Lulutin", img: "Nomi.png" },
    { name: "Grégrigry", img: "Gran_Nomi.png" },
    { name: "Métaureaulog", img: "Torivinador.png" },
    { name: "Tauracle", img: "Torivino.png" },
    { name: "Donchan", aliases: ["DON-CHAN", "Don chan", "Donchan"], img: "Don-chan.png" },
    { name: "Sabrille", img: "Rayito.png" },
    { name: "Kyryn", img: "Kyryn.png" },
    { name: "Kyrycorne", img: "Unikyryn.png" },
    { name: "Couchtar", img: "Envelo.png" },
    { name: "Noctambil", img: "Cafeino.png" },
    { name: "Herbert", img: "Acelgo.png" },
    { name: "Carnanova", img: "Morenaso.png" },
    { name: "Gloups", img: "Prestragon.png" },
    { name: "Chip-Chope", img: "Bolsadron.png" },
    { name: "Hâtila", img: "Espaoi.png" },
    { name: "Amédélègue", img: "Hazlotu.png" },
    { name: "Compte Zapzap", img: "Zappingla.png" },
    { name: "Raltesse", img: "Rataleza.png" },
    { name: "Snombéa", img: "Frivolia.png" },
    { name: "Triptyk", img: "Babamandra_A.png" },
    { name: "Dracunyan", img: "Dracunyan.png" },
    { name: "Millyeux", img: "Ojezno.png" },
    { name: "Précyeux", img: "Joyezno.png" },
    { name: "Potofeu", img: "Caldewok_A.png" },
    { name: "Rapiaf", img: "Mirlobirlo.png" },
    { name: "Zikafon", img: "Estrequito.png" },
    { name: "Babarouf", img: "Vrumbo.png" },
    { name: "Poilux", img: "Peluco.png" },
    { name: "Poil-Émile", img: "Foliculio.png" },
    { name: "Non-non", img: "No-No.png" },
    { name: "Pépésbourf", img: "Batallitos.png" },
    { name: "Adolfo Jeton", img: "Eskakeo.png" },
    { name: "Onella", img: "Lena.png" },
    { name: "Sornella", img: "Malena.png" },
    { name: "Crocho", img: "Termascino_A.png" },
    { name: "Arachnus", img: "Aracnio.png" },
    { name: "Arachnia", img: "Aracne.png" },
    { name: "Crampaud", img: "Torticolis.png" },
    { name: "Maudieuse", img: "Malmet.png" },
    { name: "Jérémya", img: "Agorerana.png" },
    { name: "Yvantouse", img: "Desolvidador.png" },
    { name: "Ed Mémoire", img: "Memorio.png" },
    { name: "Scoltine", img: "Mosquereta.png" },
    { name: "Scolérique", img: "Bronquereta.png" },
    { name: "Sirénée", img: "Nereida.png" },
    { name: "Sirènité", img: "Sirenia.png" },
    { name: "Sireine-mère", img: "Oceanida.png" },
    { name: "Mlle Coucou", aliases: ["Mlle Coucou", "Mademoiselle Coucou"], img: "Cisnia.png" },
    { name: "Draconfus", img: "Vacilagon.png" },
    { name: "Carpitaine", img: "Bergantin_A.png" },
    { name: "Déballerine", img: "Chafarina.png" },
    { name: "Savantard", img: "Repeloso.png" },
    { name: "Slurpent", img: "Octosierpe.png" },
    { name: "Melonyan", img: "Melonyan.png" },
    { name: "Oranyan", img: "Naranyan.png" },
    { name: "Kiwinyan", img: "Kiwinyan.png" },
    { name: "Vigninyan", img: "Uvanyan.png" },
    { name: "Maranyan", img: "Fresanyan.png" },
    { name: "Pastènyan", img: "Sandinyan.png" },
    { name: "Robocap", img: "Robokapp.png" },
    { name: "Robokoma", img: "Robokoma.png" },
    { name: "Robopapéti", img: "Roboabuzampa.png" },
    { name: "Robocorniot", img: "Robocantonio.png" },
    { name: "Robonoko", img: "Robonoko.png" },
    { name: "Robodracou", img: "Robodraqui.png" },
    { name: "Boucanyan", img: "Maravinyan.png" },
    { name: "Robonyan F", img: "Robonyan_2.0.png" },
    { name: "Sailornyan", img: "Sailornyan.png" },
    { name: "Maskonyan", img: "Tigrenyan.png" },
    { name: "Hovernyan", img: "Hovernyan.png" },
    { name: "Darknyan", img: "Darknyan.png" },
    { name: "Jibakoma", img: "Jibakoma.png" },
    { name: "Jetnyan", img: "Jetnyan.png" },
    { name: "Injustin", img: "Injustio.png" },
    { name: "Fielippine", img: "Malicia.png" },
    { name: "Cyrustre", img: "Implacablio.png" },
    { name: "Maudicko", img: "Inaguantablio.png" },
    { name: "Ronéan", img: "Destrukto.png" },
    { name: "Gale de bain", img: "Chupatodo.png" },
    { name: "Mabouhl", img: "Aterrahorror.png" },
    { name: "Fumella", img: "Apestula.png" },
    { name: "Fou Kappa", img: "Kappamalo.png" },
    { name: "Pariasolal", img: "Sombrio.png" },
    { name: "Fatalutin", img: "Pillastre.png" },
    { name: "Métaréaulog", img: "Toragorero.png" },
    { name: "Poulux", img: "Cardado.png" },
    { name: "Sinisrénée", img: "Trampeida.png" },
    { name: "Mlle Courroux", aliases: ["Mlle Courroux", "Mademoiselle Courroux"], img: "Malisnia.png" },
    { name: "Mélobê", img: "Keji_Do_Khan.png" },
    { name: "Geigneau", img: "Gruñon_Khan.png" },
    { name: "Bon-huiii", img: "Puergazan.png" },
    { name: "Verrascible", img: "Torreznio.png" },
    { name: "Petit Panja", img: "Pupilo_Panja.png" },
    { name: "Panja-san", img: "Panja_Pro.png" },
    { name: "Samuren", img: "Samuranguila.png" },
    { name: "Barrakéda", img: "Anguilocio.png" },
    { name: "Poulpatouch", img: "Minipulpobola.png" },
    { name: "Poulpater", img: "Pulpobola_Rey.png" },
    { name: "Avallée", img: "Aranecido.png" },
    { name: "Mont Merci", img: "Desaranecido.png" },
    { name: "Sumodon", img: "Sumodon.png" },
    { name: "Soupotori", img: "Supersumodon.png" },
    { name: "Pfffuji", img: "Desinverest.png" },
    { name: "Krakatouaaah", img: "Inverestupcion.png" },
    { name: "Lacanne", img: "Contentallo.png" },
    { name: "Canastelle", img: "Talloestrella.png" },
    { name: "Grolos", img: "Tripasqueleto.png" },
    { name: "Méganyan", img: "Meganyan.png" },
    { name: "Barbefrousse", img: "Capitan_Penas.png" },
    { name: "Tourbœillon", aliases: ["Tourbœillon", "Tourboeillon"], img: "Cicluracan.png" },
    { name: "Laure", img: "Aurea.png" },
    { name: "Marge", img: "Argenta.png" },
    { name: "Lady Perpétua", img: "Lady_Desdicha.png" },
    { name: "Lady Démona", img: "Lady_Demona.png" },
    { name: "Firmain", img: "Manojo.png" },
    { name: "Trompœil", aliases: ["Tromplœil", "Trompoeil"], img: "Torbelloptico.png" },
    { name: "Taprice", img: "Martillete.png" },
    { name: "Barbebluff", img: "Capipalante.png" },
    { name: "Mariotte", img: "Pili.png" },
    { name: "Maribass", img: "Mili.png" },
    { name: "Lady Maggie", img: "Lady_Espanto.png" },
    { name: "Filomène", img: "Kali_Mera.png" },
    { name: "Blingos", img: "Aureosqueleto.png" },
    { name: "Bogos", img: "Diamanqueleto.png" },
    { name: "Maximain", img: "Manazas.png" },
    { name: "Cycloptique", img: "Retinado.png" },
    { name: "Narinos", img: "Tomoko.png" },
    { name: "Ultramax N", img: "Ultra_N.png" },
    { name: "Ultramax K", img: "Ultra_K.png" },
    { name: "Jibanyan S", img: "Jibanyan_S.png" },
    { name: "Komasan S", img: "Komasan_S.png" },
    { name: "Komajiro S", img: "Komajiro_S.png" },
    { name: "Obskyurbi", img: "Oskyubi.png" },
    { name: "Luminoct", img: "Iluminocto.png" },
    { name: "Gargaros", img: "Gargantuo_A.png" },
    { name: "Ogralos", img: "Cazamentires_A.png" },
    { name: "Orqanos", img: "Demoniorco_A.png" },
    { name: "Jiganyan", img: "Rubeo_J.png" },
    { name: "Komak", img: "Gran_Sabueso.png" },
    { name: "Domniscian", img: "Intelecto.png" },
    { name: "Ambronzio", img: "Nulo.png" },
    { name: "Thénuki", img: "Testructor.png" },
    { name: "Infiniris", img: "Infinitio.png" },
    { name: "Chomino", img: "Expresso.png" },
    { name: "Extrabuki", img: "Kabukio.png" },
    { name: "Rouminet", "img": "Pelirrojo.png" },
  { name: "Blizzie", "img": "Grazi.png" },
  { name: "Usapyon", "img": "Usapyon.png" },
  { name: "Usapyon", "img": "Usapyon_F.png" },
  { name: "Usapyon", "img": "Usapyon_S.png" },
  { name: "Usapyon", "img": "Usapyon_M.png" },
  { name: "Usapyon", "img": "Usapyon_P.png" },
  { name: "Whisper", "img": "Whisper.png" },
  { name: "Whispocrates", aliases: ["Whispocrates", "Private Whispocrates"], "img": "Whispocrates.png" },
  { name: "Jibanyan B", "img": "Jibanyan_B.png" },
  { name: "Komasan B", "img": "Komasan_B.png" },
  { name: "Sire Nyancelot", "img": "Sir_Nyancelot.png" },
  { name: "Maginyan", "img": "Maginyan.png" },
  { name: "Momonyan", "img": "Momonyan.png" },
  { name: "Chionyan", "img": "Perronyan.png" },
  { name: "Chimpanyan", "img": "Simionyan.png" },
  { name: "Faisanyan", "img": "Faisanyan.png" },
  { name: "Démophage", "img": "Devoramonios_B.png" },
  { name: "Vampéric", "img": "Devoralmas_B.png" },
  { name: "Tata la Terreur", "img": "Cotiterror.png" },
  { name: "Marmonneur en série", "img": "Murmullamasa.png" },
  { name: "Crème Chantiwhisp", aliases: ["Crème Chantiwhisp", "Sage Moelleux"], "img": "Cremaligno.png" },
  { name: "Robonyan 28", "img": "Robonyan_28.png" },
  { name: "Pattes Rouges", "img": "Zarparroja.png" },
  { name: "Omai Tourbillonnant", "img": "Vueltomai.png" },
  { name: "Bison Antonic", "img": "Coman-cachas.png" },
  { name: "Suprarachnus", "img": "Aracnefico.png" },
  { name: "Popcorne", "img": "Belcefibio.png" },
  { name: "MoiYihin", "img": "Normalino.png" },
  { name: "Kintaronyan", "img": "Kintaronyan.png" },
  { name: "Extrabuki", "img": "Kabukio_A.png" },
  { name: "Jiganyan", "img": "Rubeo_J_A.png" },
  { name: "Komak", "img": "Gran_Sabueso_A.png" },
  { name: "Alga Sensei", "img": "Alga_Sensei.png" },
  { name: "Odyssényan", "img": "Odisenyan.png" },
  { name: "Grolos", "img": "Tripasqueleto_A.png" },
  { name: "Usapyon B", "img": "Usapyon_B.png" },
  { name: "Trempetta", "img": "Tristeresa.png" },
  { name: "Scintinoko", "img": "Estrenoko.png" },
  { name: "Seigneur Enma", "img": "Gran_Enma.png" },
  { name: "Capitaine Tonnerre", "img": "Capitan_Rayo.png" },
  { name: "Capitaine Tonnerre", "img": "Capitan_Rayo_S.png" },
  { name: "Robonyan 3000", "img": "Robonyan_3000.png" },
  { name: "Ducanin", "img": "Duque_Lametodo.png" },
  { name: "Ducfélin", "img": "Chupatricio.png" },
  { name: "Zazel", "img": "Zazel.png" },
  { name: "Zazelmar", "img": "Zazerilio.png" },
  { name: "Griffes Dorées", "img": "Zarpadorada.png" },
  { name: "Or Tourbillonnant", "img": "Vueltodorado.png" },
  { name: "Domniscian 2.0", "img": "Intelecto_Iluminado.png" },
  { name: "Roi Shogun", "img": "Shogun_Real.png" },
  { name: "Emperose", "img": "Emperador_Rosa.png" },
{ name: "Loupépin", "img": "Robin_Ful.png" },
  { name: "Antitaie", "img": "Tornalmohado.png" },
  { name: "Superfouétar", "img": "Gran_Coco.png" },
  { name: "Ronain", "img": "Minimoto.png" },
  { name: "Caliméballe", "img": "Bola_Blanda.png" },
  { name: "Battant", "img": "Bateados.png" },
  { name: "XXL de bain", "img": "Chupapremios.png" },
  { name: "El Gallardo", "img": "Guerrero_Guey.png" },
  { name: "Grande Gallardo", "img": "Huracan_Guey.png" },
  { name: "Barbokai", "img": "Barbacoo.png" },
  { name: "Moinon", "img": "Piopio_Yonohesido.png" },
  { name: "Bodruche", "img": "Globonauta.png" },
  { name: "Shurikenny", "img": "Shurikenny.png" },
  { name: "Nunchucky", "img": "Nunchucky.png" },
  { name: "Camélia", "img": "Camelia.png" },
  { name: "Bradguette", "img": "Cremallero.png" },
  { name: "Toutournemal", "img": "Metepatas.png" },
  { name: "Duc Delafeuille", "img": "Mochueloque.png" },
  { name: "Feuildechou", "img": "Todoidos.png" },
  { name: "Curryeux", "img": "Preguntio.png" },
  { name: "Curryogi", "img": "Respondio.png" },
  { name: "Lescampette", "img": "Exitio.png" },
  { name: "Boulet Frit", "img": "Cachocarne.png" },
  { name: "Épigerien", "img": "Mazorco.png" },
  { name: "Koeud", "img": "Cascarito.png" },
  { name: "Lord Écibel", "img": "Pomponio_Gala.png" },
  { name: "Steuf", "img": "Fiestuki.png" },
  { name: "Crânéidoscope", "img": "Calaveroscopio.png" },
  { name: "Lionguiste", "img": "Leonguista.png" },
  { name: "Wattson", "img": "Estatinino.png" },
  { name: "Professeur Plumage", "img": "Profesor_Avertijo.png" },
  { name: "Volroulo", "img": "Noaipapel.png" },
  { name: "Imadjinn", "img": "Jipigenio.png" },
  { name: "Aramis Taire", "img": "Miss_Teria.png" },
  { name: "Eddylapid", "img": "Renaldo.png" },
  { name: "Sodartha", "img": "Isotomas.png" },
  { name: "Mata Hase", "img": "Coneagente.png" },
  { name: "Blanche Hase", "img": "Blancacone.png" },
  { name: "Otto", "img": "Prudencio.png" },
  { name: "Dépotache", "img": "Explotacota.png" },
  { name: "Graffaël", "img": "Grafilcebu.png" },
  { name: "Chameuhllow", "img": "Chocovaca.png" },
  { name: "Pot-au-meuh", "img": "Vacaloca.png" },
  { name: "Piètros", "img": "Fracalavero.png" },
  { name: "Bricolos", "img": "Calabilidoso.png" },
  { name: "Big O'Max", "img": "Master_Chof.png" },
  { name: "Axeérator", "img": "Monte_Merario.png" },
  { name: "Navétéran", "img": "Calmarinero.png" },
  { name: "Navigarmateur", "img": "Almirante_Admirable.png" },
  { name: "Pogorille", "img": "Peter_Punki.png" },
  { name: "Mulangeur", "img": "Pantuflo.png" },
  { name: "Andrécup", "img": "Reahucio.png" },
  { name: "Zopzoparleur", "img": "Radiopatio.png" },
  { name: "Aloyauler", "img": "Filete_II.png" },
  { name: "Superobonyan", "img": "Showbonyan.png" },
  { name: "Squale Masqué", "img": "Tiburon_Tiburcio.png" },
  { name: "El Squalador", "img": "Tiburon_Jaqueton.png" },
  { name: "Flèche d'Azur", "img": "Capitan_Nublo.png" },
  { name: "Twirly Vertipiou", "img": "Sincopollo.png" },
  { name: "Tartinmarre", "img": "Brownilda.png" },
  { name: "Marceauterelle", "img": "Chapulin.png" },
  { name: "Eclopain", "img": "Apanleado.png" },
  { name: "Pain Surprise", "img": "Panduro.png" },
  { name: "Bambincroyable", "img": "Superninato.png" },
  { name: "Bambinsupportable", "img": "Superninato_Rebelde.png" },
  { name: "Bambinflammable", "img": "Superninato_Picajoso.png" },
  { name: "Jeniflair", "img": "BellonZ.png" },
  { name: "Quésacourt", "img": "Olvirunner.png" },
  { name: "Vasco de Gamiaou", "img": "Gatallanes.png" },
  { name: "Erzestine", "img": "Limonescente.png" },
  { name: "Ficheline", "img": "Tomanota.png" },
  { name: "Kay Mandeuse", "img": "Zalameria.png" },
  { name: "Jibanyan Liu Bei", "img": "Jibanyan_Liu_Bei.png" },
  { name: "Komasan Sun Ce", "img": "Komasan_Sun_Ce.png" },
  { name: "Moufrpète", "img": "Todoapesta.png" },
  { name: "Ratonglandeur", "img": "Relapache.png" },
  { name: "Espreschiot", "img": "Cafechucho.png" },
  { name: "Fortuné", "img": "Partidacio.png" },
  { name: "Tomnyan", "img": "Tomnyan.png" },
  { name: "Komaventuriers", "img": "Komaestopistas.png" },
  { name: "Faustille", "img": "Segadora.png" },
  { name: "Chocobo-nyan", "img": "Chocobonyan.png" },
  { name: "Mog-nyan", "img": "Mogurinyan.png" },
  { name: "Wobblenyan", "img": "Wobblenyan.png" },
  { name: "Wibblekoma", "img": "Wibblekoma.png" },
  { name: "Sushinyan", "img": "Sushinyan.png" },
  { name: "Tempurasan", "img": "Tempurasan.png" },
  { name: "Tenguriginal", "img": "Tenguriginal.png" },
  { name: "Ange Garudien", "img": "Angel_Garudian.png" },
  { name: "Barbucheron", "img": "Lenaciegotxea.png" },
  { name: "Double croche", "img": "Chunda_y_Tachunda.png" },
  { name: "Papi XXl", "img": "Abuzampa_XXL.png" },
  { name: "Bleunet de Bain", "img": "Albornocita_Azul.png" },
  { name: "Antoilette", "img": "Florentina.png" },
  { name: "Afronaute", "img": "Afronauta.png" },
  { name: "Charivariz", "img": "Arrocet.png" },
  { name: "Optimiss", "img": "Espe.png" },
  { name: "Benjirouette", "img": "Bellotieso.png" },
  { name: "Clic-Bull", "img": "Clican.png" },
  { name: "Dagamberge", "img": "Indeciguro.png" },
  { name: "Fourchelangue", "img": "Trabalanghi.png" },
  { name: "Papana Split", "img": "Dormidomingo.png" },
  { name: "Maudestique", "img": "Auxiliadora.png" },
  { name: "Papécolo", "img": "Abuflauta.png" },
  { name: "Les Frères Topla", "img": "Gememinencias.png" },
  { name: "Tatartelette", "img": "Repostilleja.png" },
  { name: "Javabien", "img": "Gogonzalo.png" },
  { name: "Fluorence", "img": "Esmaltina.png" },
  { name: "Maintendante", "img": "Fantasfitriona.png" },
  { name: "Survolt", "img": "Sonico.png" },
  { name: "Supervolt", "img": "Supersonico.png" },
  { name: "Auberchouine", "img": "Berenpenas.png" },
  { name: "Timouchar", "img": "Akusika.png" },
  { name: "Bazaronin", "img": "Leonerai.png" },
  { name: "Arbrézo", "img": "Trenditopico.png" },
  { name: "Arbrézo-social", "img": "Retuiterio.png" },
  { name: "Tête de lard", "img": "Panceto.png" },
  { name: "Indexter", "img": "Bilgatino.png" },
  { name: "Hacksel", "img": "Su_Hackeltad.png" },
  { name: "Flagesté", "img": "Rey_Pulsivo.png" },
  { name: "Escrocorico", "img": "Timo_Gallo.png" },
  { name: "Rocky Badboya", "img": "Rocky_Malrolla.png" },
  { name: "Charlognard", "img": "Hierodista.png" },
  { name: "M. Orthogaffe", "img": "Herrato.png" },
  { name: "TuKappa", "img": "MC_Kappa.png" },
  { name: "Sinécureuil", "img": "Tumbardillo.png" },
  { name: "Usapyon Zhongda", "img": "Usapyon_Zhongda.png" },
  { name: "Dr Néant", "img": "Dr_Nihil_Listo.png" },
  { name: "Dr Crépuscule", "img": "Dr_Nocturnia.png" },
  { name: "Entout'Hâtila", "img": "Espaya.png" },
  { name: "Cravat'en", "img": "Corbapacasa.png" },
  { name: "Déshirley", "img": "Cartairada.png" },
  { name: "Maindécis", "img": "Ambivalencio.png" },
  { name: "Carquentin", "img": "Lapo.png" },
  { name: "Théopportun", "img": "Dabombo.png" },
  { name: "Triopportun", "img": "Los_Bomboledores.png" },
  { name: "Crassiella", "img": "Amarilia.png" },
  { name: "Werner Avif", "img": "Sheriff_Agonio.png" },
  { name: "Renegainaël", "img": "Padefo.png" },
  { name: "Seulimane", "img": "Sololo.png" },
  { name: "Maracraque", "img": "Maracario.png" },
  { name: "Taïbasse", "img": "Pandalon.png" },
  { name: "Persépoil", "img": "Peluson.png" },
  { name: "Javamal", "img": "Amarguito.png" },
  { name: "Malocoeur", aliases: ["Malocoeur", Malocœur"], "img": "Nauseo.png" },
  { name: "Hadespote", "img": "Condespotico.png" },
  { name: "Jean-Mèchel", "img": "Flequipilante.png" },
  { name: "Oridjinn", "img": "Origenio.png" },
  { name: "Horridjinn", "img": "Horrogenio.png" },
  { name: "Diablotine", "img": "Fulgurilla.png" },
  { name: "Thépacap", "img": "Saltetera.png" },
  { name: "Escarcool", "img": "Don_Despacito.png" },
  { name: "Outransss", "img": "Sierpesado.png" },
  { name: "Médisansss", "img": "Cobravil.png" },
  { name: "Ébobby", "img": "Aymadrilo.png" },
  { name: "Céfasslopode", "img": "Naqueperder.png" },
  { name: "Barbuzz", "img": "Borjamar.png" },
  { name: "Tyragédie", "img": "Bebesaurio.png" },
  { name: "Catastrosaure", "img": "Destrozasaurio.png" },
  { name: "Godichezilla", "img": "Torpesaurio.png" },
  { name: "Criquetif", "img": "Luigi_Longueras.png" },
  { name: "Poulpulaire", "img": "Pulpopular.png" },
  { name: "Poulpétard", "img": "Tentanfadado.png" },
  { name: "Chocobananar", "img": "Tochacolate.png" },
  { name: "Agraisseur", "img": "Sustoleo.png" },
  { name: "Diegoïste", "img": "Reptozudo.png" },
  { name: "Entraînette", "img": "Saporientador.png" },
  { name: "Originyan", "img": "originyan.gif" },
  { name: "Scientifiborg Y", "img": "Aydroide_Y.png" },
  { name: "Roi Jibanyan", "img": "Rey_Jibanyan.png" },
  { name: "Dame Usapyon", "img": "Reina_Usapyon.png" },
  { name: "Valet Komasan", "img": "Jotamasan.png" },
  { name: "Dix de Komajiro", "img": "Diez_de_Komajiro.png" },
  { name: "As de nyan", "img": "Asnyan.png" },
  { name: "Josper", "img": "Whismodin.png" },
  { name: "Benzaiten", "img": "Benzaiten.png" },
  { name: "Hotei", "img": "Hotei.png" },
  { name: "Daikokuten", "img": "Daikokuten.png" },
  { name: "Ebisu", "img": "Ebisu.png" },
  { name: "Bishamonten", "img": "Bishamonten.png" },
  { name: "Chagellan", "img": "Gatobal_Colon.png" },
  { name: "T. Energison", aliases: ["T. Energison", "T Energison"], "img": "T_Energison.png" },
  { name: "Papy Charles", "img": "Darguin.png" },
  { name: "Le Dernier Nyanmuraï", "img": "Ultimo_Nyanmurai.png" },
  { name: "Komastar", "img": "Koma_Estrella.png" },
  { name: "Platinos", "img": "Platinum.png" },
  { name: "Papi Taliste", "img": "Abusplendido.png" },
  { name: "Saincope", "img": "Re-Q-Pera.png" },
  { name: "Corailline", "img": "Divamarina.png" },
  { name: "Asura", "img": "Todobelicoso.png" },
  { name: "Terminyanator", "img": "Terminyanator.png" },
  { name: "Supernyan", "img": "Supernyan.png" },
  { name: "Hovernyan S", "img": "Hovernyan_S.png" },
  { name: "Hovernyan Cao Cao", "img": "Hovernyan_Cao_Cao.png" },
  { name: "Yogaratoi", "img": "Yoguididacta.png" },
  { name: "Haltela", "img": "Frauduralla.png" },
  { name: "Grovide", "img": "Insaciablo.png" },
  { name: "Tristos", "img": "Penancio.png" },
  { name: "Octorbot", "img": "Venoctobot.png" },
  { name: "Orqanos Lu Bu", "img": "Demoniorco_Lu_Bu.png" },
  { name: "Kyubot", "img": "Kyubot.png" },
  { name: "Robonyan Ultime", "img": "Robonyan_Definitivo.png" },
  { name: "Taupe-modèle", "img": "Topina.png" },
  { name: "Moqua glacé", "img": "Miss_Mousse.png" },
  { name: "Normaline", "img": "populina.gif" },
  { name: "Koalanyan", "img": "Koalanyan.png" },
  { name: "Jibanyan T", "img": "jibanyan_T.gif" },
  { name: "Komasan T", "img": "komasan_T.gif" },
  { name: "Oeuxcellence", "img": "Yemajestad.png" },
  { name: "Deadcool", "img": "Cicloman.png" },
  { name: "Athlaitue", "img": "Deporchugo.png" },
  { name: "Fantimoré", "img": "Timorato_Buendia.png" },
  { name: "Ailexagère", "img": "Maripasada.png" },
  { name: "Trèchérubine", "img": "Ulteria.png" },
  { name: "Otempourmoa", "img": "Milperdones.png" },
  { name: "Céodieux", "img": "Angustianima.png" },
  { name: "Momignorante", "img": "Cutremomia.png" },
  { name: "Justicier Komasqué", "img": "Kapman.png" },
  { name: "Tofupyon", "img": "Tofupyon.png" },
  { name: "Guillotin", "img": "Dex_Capito.png" },
  { name: "Ambassadeur de charme", "img": "Embajador_Fabuloso.png" },
  { name: "Domnician", "img": "Intelecto_A.png" },
  { name: "Zazel", "img": "Zazel_A.png" },
  { name: "Procrastinocchio", "img": "Procrastinocho.png" },
  { name: "Escoffregriffe", "img": "Cofre_Cafre.png" },
  { name: "Coco Barjo", "img": "Coco_Masiel.png" },
  { name: "Whisper Kongming", "img": "Whisper_Kongming.png" },
  { name: "Jurojin", "img": "Jurojin.png" },
  { name: "Fukurokuju", "img": "Fukurokuju.png" },
  { name: "Sorcophage", "img": "Maldenotep.png" },
  { name: "Sire Trompelamor", "img": "Rey_Palmiro.png" },
  { name: "Pandore", "img": "Pandora.png" },
  { name: "Génie du rire", "img": "Ingenio.png" },
  { name: "Bastetnyan", "img": "Bastenyan.png" },
  { name: "Komanubis", "img": "Komanubis.png" },
  { name: "Baratina", "img": "Discursi.png" },
  { name: "Institours", "img": "Educoso.png" },
  { name: "Aristocorniot", "img": "Lord_Pedigri.png" },
  { name: "Mégalopaul", "img": "Urbasierpe.png" },
  { name: "Roi Pourkoidon", "img": "Pregundragon_Rey.png" },
  { name: "Zazel le bon", "img": "Zazel_Justiciero.png" },
  { name: "Domniscian 2.0", "img": "Intelecto_Iluminado_A.png" },
  { name: "Enma l'Ancien", "img": "Enma_Ancestral.png" },
  { name: "Seigneur Enma 2.0", "img": "Gran_Enma_Iluminado.png" },
  { name: "Somnoracle", "img": "Rollaculo.png" },
  { name: "Shivatenguerre", "img": "Maharazas.png" },
  { name: "Cymbaline", "img": "Cimbalina.png" },
  { name: "Gromel", "img": "Masculloso.png" },
  { name: "Vociféro", "img": "Vociferio.png" },
  { name: "Glapie", "img": "Aviguito_Pio.png" },
  { name: "Affolanterne", "img": "Frustrolillo.png" },
  { name: "Meuhlinda", "img": "Bovida.png" },
  { name: "Hiivon", "img": "Equinio.png" },
  { name: "Turboss", "img": "Pecificador.png" },
  { name: "Alpinella", "img": "Alpina.png" },
  { name: "Lunatio", "img": "Seleno.png" },
  { name: "KJ", "img": "KJ.png" },
  { name: "Enma Solaire", "img": "Enma_Solar.png" },
  { name: "Enma Infini", "img": "Enma_Infinito.png" },
  { name: "Enma Funèbre", "img": "Enma_Umbrio.png" },
  { name: "Indiana Jaws", "img": "tibu_Jones.gif" },
  { name: "M. Spioche", "img": "vulcavador.gif" },
  { name: "Zombigoût", "img": "adoleszombi.gif" },
  { name: "Nyansès II", "img": "nyanses_II.gif" },
  { name: "Néfertyrannie", "img": "Miopatra.png" },
  { name: "Cocassepied", "img": "mazado_de_la_Calzada.gif" },
  { name: "El Dragonor", "img": "Dradorado.png" },
  { name: "Phémniscian", "img": "Fenixtelecto.png" },
  { name: "Fratracteur", "img": "Chatarrenstein.png" },
  { name: "Supermanager", "img": "Supergerente.png" },
  { name: "Thibonimenteur", "img": "Ilusionisto.png" },
  { name: "Agent X", "img": "Camorro.png" },
  { name: "Agent Rixe", "img": "Diavolo.png" },
  { name: "Minustrel", "img": "Flautista_de_Malmelin.png" },
  { name: "Yo-kaiju", "img": "Gamero.png" },
  { name: "Yopple-Bot", "img": "Yopple-Bot.png" },
  { name: "No-Bot", "img": "No-Bot.png" },
  { name: "Dodorothée", "img": "Nocturnia.png" },
  { name: "King Keskler", "img": "Ray_Baqueto.png" },
  { name: "Don Morleone", "img": "Don_Crueleone.png" },
  { name: "Don Spiration", "img": "Don_Conspirazione.png" },
  { name: "Magnustrel", "img": "Flautiscolito.png" },
  { name: "Voltéophyte", "img": "Duocolito.png" },
  { name: "Didgéophyte", "img": "Cantacolito.png" },
  { name: "Tornadoculaire", "img": "Ciclonojo.png" },
  { name: "Clochemar", "img": "Caballero_Hueco.png" },
  { name: "Rôdin", "img": "Paticio.png" },
  { name: "Orqéophyte", "img": "Demoniorcolito.png" },
  { name: "Karmagister", "img": "Iluminazen.png" },
  { name: "Boucanos", "img": "Capitan_Botin.png" },
  { name: "Garegamelle", "img": "Chef_Ricote.png" },
  { name: "Sequestrella", "img": "Doncella_de_la_Ruina.png" },
  { name: "Shamanaconda", "img": "Necrocobra.png" },
  { name: "Don Dorleone", "img": "Don_Aureone.png" },
  { name: "Mécagolem", "img": "Icarus.png" },
  { name: "Ténorque", "img": "Ballenato.png" },
  { name: "Morquis", "img": "Cachaslote.png" },
  { name: "Hacharné", "img": "El_Carnicero.png" },
  { name: "Hypertaupe", "img": "Topoderoso.png" },
  { name: "Ultime Nyanmurai", "img": "El_Ultimisimo_Nyanmurai.png" },
 { name: "Ogamitaoshi", img: "Ogamitaoshi.png" },
    { name: "Capitaine Dodo", aliases: ["Capitaine Dodo", "Captain Dodo"], img: "Capitan_Dodo.png" },
    { name: "Chousensha", img: "Chosensha.png" },
    { name: "Monomaneking", img: "Monomaneking.png" },
    { name: "Morigami Rex", img: "Morigami_Rex.png" },
    { name: "Wibblejiro", aliases: ["Wibblejiro", "Wobblejiro", "Punijiro"], img: "Wibblejiro.png" },
    { name: "Shourinji", img: "Shourinji.png" },
    { name: "Raise Girl", img: "Raise_Girl.png" },
    { name: "Katenshi", img: "Katenshi.png" },
    { name: "Futekusaru", img: "Futekusaru.png" },
    { name: "Usapyon T", aliases: ["Usapyon T", "T-Usapyon"], img: "Usapyon_T.png" },
    { name: "Maizo Tokugawa", img: "Maizo_Tokugawa.png" },
    { name: "Al Baccino", aliases: ["Al Baccino", "Are Bacchino"], img: "Al_Baccino.png" },
    { name: "Grolos T", aliases: ["Grolos T", "Gashadokuro T"], img: "Tripasqueleto_T.png" },
    { name: "Kaneuki-hime", img: "Kaneuki-hime.png" },
    { name: "AkiraMEN", img: "AkiraMEN.png" },
    { name: "Omoutsubo", img: "Omoutsubo.png" },
    { name: "Naga Raja", img: "Naga_Raja.png" },
    { name: "Tribu Doyagari", aliases: ["Doyagari", "Doyagari-zoku"], img: "Tribu_Doyagari.png" },
    { name: "Doya Osa", img: "Doya_Osa.png" },
    { name: "Vascoda Gama", img: "Vascoda_Gama.png" },
    { name: "Shogunyan C", aliases: ["Shogunyan C", "Crystal Shogunyan"], img: "Shogunyan_Cristal.png" },
    { name: "Wobblehover", aliases: ["Wobblehover", "Wibblehover", "Punifuyu"], img: "Wobblehover.png" },
    { name: "Jibanyan T G", aliases: ["Jibanyan T G", "T-Jibanyan G"], img: "Jibanyan_T_G.png" },
    { name: "Jibanyan D", img: "Jibanyan_D.png" },
    { name: "Komasan T G", aliases: ["Komasan T G", "T-Komasan G"], img: "Komasan_T_G.png" },
    { name: "Komasan D", img: "Komasan_D.png" },
    { name: "Indiana Jaws G", aliases: ["Indiana Jaws G", "Indy Jaws G"], img: "Tibu_Jones_G.png" },
    { name: "Cindy Jaws", img: "Cindy_Jaws.png" },
    { name: "M. Spioche G", aliases: ["M Spioche G", "Mr. Scoop G"], img: "Vulcavador_G.png" },
    { name: "Zombigoût G", aliases: ["Zombigoût G", "Zom B Chopper G"], img: "Adoleszombi_G.png" },
    { name: "Nyansès II G", aliases: ["Nyansès II G", "Neko II G"], img: "Nyanses_II_G.png" },
    { name: "Yodelsen", img: "Yodelsen.png" },
    { name: "Narcis II", img: "Narciso_II.png" },
    { name: "Zappadokia", img: "Zappadokia.png" },
    { name: "Mademoaiselle", img: "Mademoaiselle.png" },
    { name: "Pierre de Rosette", aliases: ["Pierre de Rosette", "Rosetta Stone"], img: "Piedra_Rosetta.png" },
    { name: "Doescalibur", img: "Doescalibur.png" },
    { name: "Encore Dead", img: "Encore_Dead.png" },
    { name: "Armaterasu", aliases: ["Armaterasu", "Armorterasu", "Amaterasu"], img: "Armaterasu.png" },
    { name: "Dandory", img: "Dandory.png" },
    { name: "Spatto", img: "Spatto.png" },
    { name: "Tanto", img: "Tanto.png" },
    { name: "Kirene", img: "Kirene.png" },
    { name: "Toranka", img: "Toranka.png" },
    { name: "Catleen", img: "Catleen.gif" },
    { name: "Gustaf", img: "Gustaf.png" },
    { name: "Gowin", img: "Gowin.png" },
    { name: "Seirei Banbarayar", img: "Seirei_Banbarayar.png" },
    { name: "Enma", img: "Enma.png" },
    { name: "Enma Sombre", aliases: ["Enma Sombre", "Yami Enma"], img: "Enma_Oscuro.png" },
    { name: "Baron Ananta", img: "Lord_Ananta.png" },
    { name: "Enma Meiou Maka", img: "Enma_Meiou_Maka.png" },
    { name: "Enmanyan", aliases: ["Enmanyan", "Enma Neko'ou Matatabi"], img: "Enmanyan.png" },
    { name: "Enma Ryuuou Mizuchi", img: "Enma_Ryuuou_Mizuchi.png" },
    { name: "Enma Raou Tekakku", img: "Enma_Raou_Tekakku.png" },
    { name: "Lord Acala", aliases: ["Lord Acala", "Fudou Myouou"], img: "Lord_Acala.png" },
    { name: "Chi Ma Tree", img: "Chi_Ma_Tree.png" },
    { name: "BaiKING", img: "BaiKING.png" },
    { name: "Momiroir", img: "Boogiemum.png" },
    { name: "Kanibouzu", img: "Kanibouzu.png" },
    { name: "Orifalcon", img: "Orifalcon.png" },
    { name: "WaNEWdo", img: "WaNEWdo.png" },
    { name: "Dark Master", img: "Dark_Master.png" },
    { name: "Billy le Vagabond", aliases: ["Billy le Vagabond", "Sasurai no Billy"], img: "Billy_el_Errante.png" },
    { name: "Gowin", img: "Gowin_B.png" },
    { name: "Kanaendesu", img: "Kanaendesu.png" },
    { name: "Majin Banbarayar", img: "Majin_Banbarayar.png" },
    { name: "Yodelsen", img: "Yodelsen_B.png" },
    { name: "Zircondor", img: "Zircondor.png" },
      { name: "Jabow", "img": "Jabow.png" },
  { name: "Shirokuma", "img": "Shirokuma.png" },
  { name: "Harrisson", "img": "Punkupine.png" },
  { name: "Poulpardon", "img": "Sorrypus.png" },
  { name: "McKraken", "img": "McKraken.png" },
  { name: "Granpapéti", "img": "Abuzampa.gif" },
  { name: "Pakkun", aliases: ["Pakkun", "Gabriel"], "img": "Pakkun.gif" },
  { name: "Kyunshii", aliases: ["Kyunshii", "Zukkyunshii"], "img": "Kyunshii.gif" },
  { name: "Hare-onna", aliases: ["Hare-onna", "Ame-onna"], "img": "Hare-onna.gif" },
  { name: "Kakurenbou", aliases: ["Kakerenbou", "Inaiinaibaa"], "img": "Kakurenbou.gif" },
  { name: "Blizzaria", "img": "Granizia.gif" },
  { name: "Damona", "img": "Damona.gif" },
  { name: "Zazel", "img": "Zazel_2040.png" },
  { name: "Daniel", aliases: ["Daniel", "Big Danny"], "img": "Daniel.gif" },
  { name: "Choky", aliases: ["Choky", "Shiomaneki"], "img": "Choky.gif" },
  { name: "Feulion", "img": "Flamileon.gif" },
  { name: "Itashikatanashi", aliases: ["Itashikatanashi", "Yamuwoen"], "img": "Itashikatanashi.gif" },
  { name: "Saya", aliases: ["Saya", "Makenki"], "img": "Saya.gif" },
  { name: "Tontonerre", "img": "Papa_Rayo.gif" },
  { name: "Octorgone", "img": "Venocto.gif" },
  { name: "Octorgombre", "img": "Venoctoscuro.gif" },
  { name: "Shogunyan", "img": "Shogunyan.gif" },
  { name: "Komashura", "img": "Komasura.gif" },
  { name: "Arachnus", "img": "Aracnio.gif" },
  { name: "Lil' Acala", aliases: ["Lil' Acala", "Lil Acala", "Fudou Myouou Boy"], "img": "Lil'_Acala.png" },
  { name: "Honmaguro-taisho", aliases: ["Honmaguro-taisho", "Magulodon", "Neptuna"], "img": "Honmaguro-taisho.gif" },
  { name: "Semicolon", aliases: ["Semicolon", "Semirongu", "Bugaboo"], "img": "Semicolon.gif" },
  { name: "Komasan", "img": "Komasan.gif" },
  { name: "Komajiro", "img": "Komajiro.gif" },
  { name: "Banchou", aliases: ["Banchou", "Bourei Banchou", "Basher"], "img": "Banchou.gif" },
  { name: "Noko", "img": "Noko.gif" },
  { name: "Dragô", "img": "Dragon_Azur.gif" },
  { name: "Fuu-kun", aliases: ["Fuu-kun", "Fuujin"], "img": "Fuu-kun.gif" },
  { name: "Rai-chan", aliases: ["Rai-chan", "Raijin"], "img": "Rai-chan.gif" },
  { name: "Crapop", "img": "Eleganfibio.gif" },
  { name: "Jibanyan", "img": "Jibanyan.gif" },
  { name: "Uribou", aliases: ["Uribou", "Inosasaou"], "img": "Uribou.gif" },
  { name: "Hamham", aliases: ["Hamham", "Abraham"], "img": "Hamham.gif" },
  { name: "Doyapon", aliases: ["Doyapon", "Doudanuki"], "img": "Doyapon.gif" },
  { name: "Kyubi", "img": "Kyubi.gif" },
  { name: "Barakabo", "img": "Nievacolas.gif" },
  { name: "Charlie", aliases: ["Charlie", "Ghostcycle"],  "img": "Charlie.gif" },
  { name: "Kezurin", aliases: ["Kezurin", "Jinkotsukezuri"], "img": "Kezurin.gif" },
  { name: "Marmitor", aliases: ["Marmitor", "Zundoumaru", "Shiryou no Dokudoku-nabe"], "img": "Hot_Pot.gif" },
  { name: "Télémir", "img": "Telespejo.gif" },
  { name: "Jinta", aliases: ["Jinta", "Jingeki"], "img": "Jinta.gif" },
  { name: "Kantaro", aliases: ["Kantaro", "Jihanki"], "img": "Kantaro.gif" },
  { name: "Tidynator", aliases: ["Tidynator", "Robonyan 00"], "img": "Tidynator.gif" },
  { name: "Kiborikkuma", aliases: ["Kiborikkuma", "Onikuma"], "img": "Kiborikkuma.gif" },
  { name: "Junior", aliases: ["Junior", "Burning Dragon"], "img": "Junior.gif" },
  { name: "Whisper", "img": "Whisper_2024.png" },
  { name: "Sly", aliases: ["Sly", "Slimamander", "Super Sly", "Mitsumata Ghidorah", "Micchy"], "img": "Sly.gif" },
  { name: "Becchan", aliases: ["Becchan", "Nuttarabeccha"], "img": "Becchan.gif" },
  { name: "Dameboy", aliases: ["Dameboy", "Zettai Guardman"], "img": "Dameboy.gif" },
  { name: "Fukurou", "img": "Fukurou.png" },
  { name: "Domniscian", "img": "Intelecto.gif" },
  { name: "Ogu Togu Mogu", aliases: ["Ogu Togu Mogu", "Ogu, Togu et Mogu", "Ogu, Togu & Mogu"], "img": "Ogu_Togu_Mogu.png" },
  { name: "Voidera", aliases: ["Voidera", "Douketsu"], "img": "Voidera.png" },
  { name: "Shutendouji", aliases: ["Shutendouji", "Sodartha"], "img": "Shutendouji.png" },
  { name: "Juno", aliases: ["Juno", "Shuka"], "img": "Juno.png" },
  { name: "Boreas", aliases: ["Boreas", "Gentou"], "img": "Boreas.png" },
  { name: "Eurus", aliases: ["Eurus", "Hakushuu"], "img": "Eurus.png" },
  { name: "Saros", aliases: ["Saros", "Kuuten"], "img": "Saros.png" },
  { name: "Enma Démoniaque", aliases: ["Enma Démoniaque", "Yasha Enma", "Enma 2.0", "Kakusei Enma"], "img": "Yasha_Enma.gif" },
  { name: "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa.png" },
  { name: "Kenshin Amaterasu", aliases: ["Kenshin Amaterasu", "Amaterasu"], "img": "Kenshin_Amaterasu.png" },
  { name: "Suu-san", "img": "Suu-san.png" },
  { name: "Nomi", aliases: ["Nomi", "Zashiki-warashi", "Tengu'ou Kurama"], "img": "Gnomey.gif" },
  { name: "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa_LS.png" },
  { name: "Kukuri-hime", "img": "Kukuri-hime.png" },
  { name: "Gesshin Tsukuyomi", aliases: ["Gesshin Tsukuyomi", "Tsukuyomi"], "img": "Gesshin_Tsukuyomi.png" },
  { name: "Abyssinyan", aliases: ["Abyssinyan", "Kaibyou Kamaitachi", "Neko'ou Bastet"], "img": "Gusto.gif" },
  { name: "Kawauso", "img": "Kawauso.png" },
  { name: "Tamamo", aliases: ["Tamamo", "Tamamo-no-mae"], "img": "Tamamo.gif" },
  { name: "Gyuuki", "img": "Gyuuki.png" },
  { name: "Narigama", "img": "Narigama.png" },
  { name: "Blobgoblin", "img": "Blobgoblin.png" },
  { name: "Azukiarai", "img": "Azukiarai.png" },
  { name: "Kappa", aliases: ["Kappa", "Kappa'ou Sagojou"], "img": "Kappa.gif" },
  { name: "Shien", "img": "Shien.png" },
  { name: "Gran Enma Gouen", aliases: ["Gran Enma Gouen", "Gran Enma", "Enma Daiou"], "img": "Gran_Enma_Gouen.png" },
  { name: "Naviwan", "img": "Naviwan.png" },
  { name: "Konsaru", "img": "Konsaru.png" },
  { name: "Drone", "img": "Dron.png" },
  { name: "Extraterrestre", aliases: ["Extraterrestre", "Mikakunin", "Membre de la tribu Mikakunin"], "img": "Miembro_Mikakunin.png" },
  { name: "Kitaro", "img": "Kitaro.png" },
  { name: "Papa Globule", aliases: ["Papa Globule", "Medama Oyaji"], "img": "Papa_Ojo.png" },
  { name: "Triptyk", "img": "Babamandra_SS.png" },
  { name: "Medamanbou", aliases: ["Medamanbou", "œil de triptyk"], "img": "Medamanbou.png" },    
  { name: "Jingeki", "img": "Jingeki.png" },
  { name: "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa_Boss.png" },
  { name: "Shinmagunshin Fukurou", aliases: ["Shinmagunshin Fukurou", "Fukurou Corrompu"], "img": "Shinmagunshin_Fukurou.png" },
  { name: "Lady Arachnia", aliases: ["Lady Arachnia", "Jorogumo"], "img": "Lady_Aracne.png" },
  { name: "Tamamo-no-mae", aliases: ["Tamamo-no-mae", "Tamamo no mae"], "img": "Tamamo-no-mae.png" },
  { name: "Shinma Voidera", aliases: ["Shinma Voidera", "Shinma Douketsu", "Voidera Corrompu"], "img": "Voidera_Boss.png" },
  { name: "Shien", "img": "Shien.png" },
  { name: "Shinma Ananta", aliases: ["Shinma Ananta", "Shinma Kaira"], "img": "Ananta_Boss.png" },
  { name: "Overseer", aliases: ["Overseer", "Soranaki"], "img": "Overseer.png" },
  { name: "Maten Overseer", aliases: ["Maten Overseer", "Maten Soranaki"], "img": "Maten_Overseer.png" },
  { name: "Raidenryu", "img": "Raidenryu.png" },
  { name: "Ananta Sombre", aliases: ["Ananta Sombre", "Yami Kaira"], "img": "Ananta_Oscuro.png" },
  { name: "Acala Céleste", aliases: ["Acala Celestial", "Fudou Myouou Ten"], "img": "Acala_Celestial.png" },
  { name: "Acala Exalté", aliases: ["Acala Exalté", "Acala Exalted", "Fudou Myouou Kai"], "img": "Acala_Exaltado.png" },
  { name: "Suzaku", "img": "Suzaku.png" },
  { name: "Genbu", "img": "Genbu.png" },
  { name: "Asura", "img": "Asura.png" },
  { name: "Byakko", "img": "Byakko.png" },
  { name: "Goemon", "img": "Goemon.png" },
  { name: "Matsu", aliases: ["Matsu", "Omatsu"], "img": "Matsu.png" },
  { name: "Minamoto", aliases: ["Minamoto", "Yoshitsune"], "img": "Minamoto.png" },
  { name: "Benkei", "img": "Benkei_P.png" },
  { name: "Kyryn", "img": "Kyryn_C.png" },
  { name: "Suzaku", "img": "Suzaku_C.png" },
  { name: "Genbu", "img": "Genbu_C.png" },
  { name: "Byakko", "img": "Byakko_C.png" },
  { name: "Souryuu", "img": "Souryuu.png" },
  { name: "Gunshin Susanoo", aliases: ["Gunshin Susanoo", "Susanoo"], "img": "Gunshin_Susanoo.png" }
];

let score = 0; 
let gameEnded = false; // Evita cambios una vez terminado el juego
const unlockedYoKai = new Set(); // Registro de Yo-kai desbloqueados por índice

// Normalizar la entrada del usuario (sin tildes y en minúsculas)
function normalizeString(str) {
    return str.normalize("NFD").replace(/[̀-\u036f]/g, "").toLowerCase();
}

// Crear el objeto de audio una sola vez
let getSound = new Audio("get.mp3");

// Reproducir sonido cuando se desbloquea un Yo-kai (sin solapamiento)
function playGetSound() {
    if (!getSound.paused) {
        getSound.pause(); // Detener el sonido actual si ya está reproduciéndose
        getSound.currentTime = 0; // Reiniciar el sonido al principio
    }
    getSound.play(); // Reproducir el sonido
}

// Actualizar la puntuación en formato (adivinados / totales)
function updateScoreDisplay() {
    const scoreDisplay = document.getElementById("score");
    scoreDisplay.textContent = `${score}/${yoKaiList.length}`;
}

// Verificar la respuesta del usuario
function checkAnswer() {
    if (gameEnded) return; // Si el juego ha terminado, no hacer nada

    const userAnswer = normalizeString(document.getElementById("answer-input").value.trim());

    let correctGuess = false; // Bandera para reproducir el sonido solo si hay aciertos

    yoKaiList.forEach((yoKai, index) => {
        // Normaliza todos los nombres asociados al Yo-kai
        const normalizedNames = [yoKai.name, ...(yoKai.aliases || [])].map(name => normalizeString(name));

        // Si la respuesta coincide con alguno de los nombres y no ha sido desbloqueado
        if (normalizedNames.includes(userAnswer) && !unlockedYoKai.has(index)) {
            const yoKaiImg = document.getElementById(`yo-kai${index + 1}`);
            if (yoKaiImg && yoKaiImg.src.includes("No-kai4.png")) {
                yoKaiImg.src = yoKai.img; // Actualiza la imagen

                // Añadir clase para animación
                yoKaiImg.classList.add("yokai-unlocked");
                yoKaiImg.addEventListener("animationend", () => {
                    yoKaiImg.classList.remove("yokai-unlocked"); // Quitar clase tras animación
                });

                unlockedYoKai.add(index); // Marcar el Yo-kai como desbloqueado
                score++;
                correctGuess = true; // Se encontró un acierto
            }
        }
    });

    if (correctGuess) {
        playGetSound(); // Reproducir sonido solo si hubo un acierto
        updateScoreDisplay(); // Actualizar puntuación
        document.getElementById("answer-input").value = ""; // Borra la respuesta después de un acierto
    }

    checkGameEnd(); // Verifica si el juego ha terminado
}

// Verificar si el juego ha terminado (cuando se han adivinado todos los Yo-kai)
function checkGameEnd() {
    if (score === yoKaiList.length) {
        gameEnded = true;
        stopTimer(); // Detener el temporizador
        showCongratsImage(); // Mostrar imagen de "¡Felicidades!"
    }
}

function showCongratsImage() {

    // Detener temporizador
    stopTimer();

    // Obtener tiempo final mostrado
    const tiempoTotal = document.getElementById("time").textContent;

    // Sonido de victoria
    const victorySound = new Audio("congrats.mp3");
    victorySound.volume = 0.8;
    victorySound.play().catch(() => {});

    // Panel lateral
    const finalPanel = document.createElement("div");
    finalPanel.style.position = "fixed";
    finalPanel.style.top = "0";
    finalPanel.style.right = "-350px";
    finalPanel.style.width = "320px";
    finalPanel.style.height = "100%";
    finalPanel.style.backgroundColor = "#0b2a4a";
    finalPanel.style.color = "white";
    finalPanel.style.padding = "20px";
    finalPanel.style.boxSizing = "border-box";
    finalPanel.style.zIndex = "1000";
    finalPanel.style.fontFamily = "Arial, sans-serif";
    finalPanel.style.display = "flex";
    finalPanel.style.flexDirection = "column";
    finalPanel.style.transition = "right 0.6s ease";

    // Botón cerrar
    const closeBtn = document.createElement("div");
    closeBtn.textContent = "✖";
    closeBtn.style.position = "absolute";
    closeBtn.style.top = "15px";
    closeBtn.style.right = "15px";
    closeBtn.style.cursor = "pointer";
    closeBtn.style.fontSize = "18px";

    closeBtn.addEventListener("click", () => {
        finalPanel.style.right = "-350px";
        setTimeout(() => finalPanel.remove(), 600);
    });

    // Título
    const title = document.createElement("h2");
    title.textContent = `Bravo ! Vous avez deviné tous les Yo-kai en ${tiempoTotal}`;
    title.style.marginTop = "40px";
    title.style.marginBottom = "30px";
    title.style.fontSize = "22px";

    // Texto Twitter
    const followText = document.createElement("p");
    followText.innerHTML = `
        Si cela vous a plu, pourquoi ne pas me suivre sur Twitter ?: 
        <a href="https://x.com/salty_baconV2" target="_blank" style="color:#4fc3ff; text-decoration:none;">
        @Salty_BaconV2
        </a>
    `;
    followText.style.fontSize = "16px";
    followText.style.marginTop = "auto";

    // Montaje
    finalPanel.appendChild(closeBtn);
    finalPanel.appendChild(title);
    finalPanel.appendChild(followText);
    document.body.appendChild(finalPanel);

    // Animación de entrada
    setTimeout(() => {
        finalPanel.style.right = "0";
    }, 50);
}


// Temporizador
let startTime;
let timerInterval;

function startTimer() {
    startTime = Date.now();
    timerInterval = setInterval(updateTimer, 1000);
}

function updateTimer() {
    const currentTime = Date.now();
    const elapsedTime = currentTime - startTime;

    const hours = Math.floor(elapsedTime / (1000 * 60 * 60));
    const minutes = Math.floor((elapsedTime % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((elapsedTime % (1000 * 60)) / 1000);

    const formattedTime = `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
    document.getElementById("time").textContent = formattedTime;
}

function stopTimer() {
    clearInterval(timerInterval);
}

// Manejador de evento: validación automática con "input"
document.getElementById("answer-input").addEventListener("input", checkAnswer);

// Inicializar el marcador y temporizador al cargar la página
updateScoreDisplay(); // Inicializa la puntuación en 0/total
startTimer();

window.addEventListener("beforeunload", (event) => {
    if (score > 0) { // Mostrar advertencia solo si hay progreso
        event.preventDefault();
        event.returnValue = "¿Estás seguro de que quieres salir? Se perderá todo el progreso.";
    }
});
