const yoKaiList = [
    { name: "Pandle", img: "alcaldero.png" },
    { name: "Undy", img: "sinna.png" },
    { name: "Tanbo", img: "sinnareno.png" },
    { name: "Cutta-nah", img: "katano.png" },
    { name: "Cutta-nah-nah", img: "katananai.png" },
    { name: "Slacka-slash", img: "katakroken.png" },
    { name: "Mochismo", img: "mochimacho.png" },
    { name: "Minochi", img: "machimio.png" },
    { name: "Helmsman", img: "yelmandante.png" },
    { name: "Reuknight", img: "juntollero.png" },
    { name: "Corptain", img: "genedaver.png" },
    { name: "Blazion", img: "flamileon.png" },
    { name: "Quaken", img: "tembloleon.png" },
    { name: "Siro", img: "sirleon.png" },
    { name: "Chansin", img: "ludorai.png" },
    { name: "Sheen", img: "lustre.png" },
    { name: "Snee", img: "Furtre.png" },
    { name: "Gleam", img: "dortre.png" },
    { name: "Benkei", img: "benkei.png" },
    { name: "B3-NK1", img: "b3-nk1.png" },
    { name: "Sushiyama", img: "sushiyama.png" },
    { name: "Kapunki", img: "kapunki.png" },
    { name: "Beetler", img: "lucharabajo.png" },
    { name: "Betall", img: "camperabajo.png" },
    { name: "Cruncha", img: "chafarabajo.png" },
    { name: "Zerberker", img: "osfurio.png" },
    { name: "Snartle", img: "sacoco.png" },
    { name: "Snotsolong", img: "mokopavo.png" },
    { name: "Duchoo", img: "pachus.png" },
    { name: "Wazzat", img: "komemo.png" },
    { name: "Dummkap", img: "tontolin.png" },
    { name: "D'wanna", img: "yopaso.png" },
    { name: "N'more", img: "puf.png" },
    { name: "Q'wit", img: "yanomas.png" },
    { name: "Lafalotta", img: "algazara.png" },
    { name: "Blips", img: "labizula.png" },
    { name: "Tattletell", img: "cotilleja.png" },
    { name: "Tattlecast", img: "marulleja.png" },
    { name: "Skranny", img: "esquelleja.png" },
    { name: "Cupistol", img: "cupistolo.png" },
    { name: "Casanuva", img: "casanovo.png" },
    { name: "Casanono", img: "casanono.png" },
    { name: "Signibble", img: "ondivoro.png" },
    { name: "Signiton", img: "coberturo.png" },
    { name: "Statiking", img: "estatinarca.png" },
    { name: "Mirapo", img: "telespejo.png" },
    { name: "Mircle", img: "malpejismo.png" },
    { name: "Illoo", img: "iluho.png" },
    { name: "Elloo", img: "eluho.png" },
    { name: "Alloo", img: "ubiuho.png" },
    { name: "Espy", img: "trilepata.png" },
    { name: "Infour", img: "tetrariosa.png" },
    { name: "Tengu", img: "tengu.png" },
    { name: "Flengu", img: "flamngu.png" },
    { name: "Kyubi", img: "kyubi.png" },
{ name: "Frostail", img: "nievacolas.png" },
{ name: "Dulluma", img: "tentelento.png" },
{ name: "Darumacho", img: "tentemacho.png" },
{ name: "Goruma", img: "tenterila.png" },
{ name: "Noway", img: "nihablar.png" },
{ name: "Impass", img: "impas.png" },
{ name: "Walldin", img: "murallin.png" },
{ name: "Armsman", img: "lorigon.png" },
{ name: "Fidgephant", img: "inquielifante.png" },
{ name: "Touphant", img: "perselefante.png" },
{ name: "Blowkade", img: "globqueo.png" },
{ name: "Ledballoon", img: "globtundente.png" },
{ name: "Mad Mountain", img: "montaña_loca.png" },
{ name: "Lava Lord", img: "lord_lava.png" },
{ name: "Roughraff", img: "rebelcebu.png" },
{ name: "Badude", img: "caporrista.png" },
{ name: "Bruff", img: "hermanion.png" },
{ name: "Rhinoggin", img: "pegarabajo.png" },
{ name: "Rhinormous", img: "enormarabajo.png" },
{ name: "Hornaplenty", img: "cuernarabajo.png" },
{ name: "Castelius III", img: "castelius_III.png" },
{ name: "Castelius II", img: "castelius_II.png" },
{ name: "Castelius I", img: "Castelius_I.png" },
{ name: "Castelius Max", img: "Maxicastelius.png" },
{ name: "Robonyan", img: "robonyan.png" },
{ name: "Goldenyan", img: "aureonyan.png" },
{ name: "Dromp", img: "pom.png" },
{ name: "Swosh", img: "flus.png" },
    { name: "Dazzabel", img: "deslumbrella.png" },
    { name: "Rattelle", img: "rechinella.png" },
    { name: "Skelebella", img: "esquelebella.png" },
    { name: "Cadin", img: "ningarra.png" },
    { name: "Cadable", img: "habilgarra.png" },
    { name: "Singcada", img: "cantigarra.png" },
    { name: "Pupsicle", img: "escanlofrio.png" },
    { name: "Chilhuahua", img: "frihuahua.png" },
    { name: "Swelterrier", img: "lavadenco.png" },
    { name: "Jibanyan", img: "jibanyan.png" },
    { name: "Thornyan", img: "espinyan.png" },
    { name: "Baddinyan", img: "pelochnyan.png" },
    { name: "Walkappa", img: "kappandante.png" },
    { name: "Appak", img: "kappadachin.png" },
    { name: "Supyo", img: "kapparfista.png" },
    { name: "Komasan", img: "komasan.png" },
    { name: "Komane", img: "komaleon.png" },
    { name: "Komajiro", img: "komajiro.png" },
    { name: "Komiger", img: "komatigrado.png" },
    { name: "Baku", img: "baku.png" },
    { name: "Whapir", img: "blanpir.png" },
    { name: "Shmoopie", img: "pufipatitas.png" },
    { name: "Pinkipoo", img: "pufilindo.png" },
    { name: "Pookivil", img: "pufimaloso.png" },
    { name: "Frostina", img: "fristina.png" },
    { name: "Blizzaria", img: "granizia.png" },
    { name: "Damona", img: "damona.png" },
{ name: "Wiglin", img: "cimbron.png" },
{ name: "Steppa", img: "pasodon.png" },
{ name: "Rhyth", img: "ritma.png" },
{ name: "Wantston", img: "kieroto.png" },
{ name: "Grubsnitch", img: "zampo.png" },
{ name: "Hungramps", img: "abuzampa.png" },
{ name: "Hungorge", img: "gargazampa.png" },
{ name: "Grainpa", img: "aburroz.png" },
{ name: "Lodo", img: "nomeda.png" },
{ name: "Chippa", img: "opti.png" },
{ name: "Enerfly", img: "enerposa.png" },
{ name: "Enefly", img: "eneposa.png" },
{ name: "Betterfly", img: "mejorposa.png" },
{ name: "Peppillon", img: "vivariposa.png" },
{ name: "Happierre", img: "felisonte.png" },
{ name: "Reversa", img: "reversa.png" },
{ name: "Reversette", img: "reversada.png" },
{ name: "Ol' Saint Trick", img: "tricotom.png" },
{ name: "Ol' Fortune", img: "dadivo.png" },
{ name: "Rollen", img: "bolilete.png" },
{ name: "Dubbles", img: "doblilete.png" },
{ name: "Papa Bolt", img: "papa_rayo.png" },
{ name: "Uncle Infinite", img: "tio_infinito.png" },
{ name: "Mama Aura", img: "mama_aura.png" },
{ name: "Auntie Heart", img: "tita_corazon.png" },
{ name: "Leadoni", img: "noguio.png" },
{ name: "Mynimo", img: "topami.png" },
{ name: "Ake", img: "algio.png" },
{ name: "Payn", img: "agujeto.png" },
{ name: "Agon", img: "machaka.png" },
{ name: "Negatibuzz", img: "negatisquito.png" },
{ name: "Moskevil", img: "deprisquito.png" },
{ name: "Scritchy", img: "picorron.png" },
{ name: "Dimmy", img: "nomeven.png" },
{ name: "Blandon", img: "nostoy.png" },
{ name: "Nul", img: "nul_.png" },
{ name: "Hidabat", img: "encielago.png" },
{ name: "Abodabat", img: "caserielago.png" },
{ name: "Belfree", img: "ermicielago.png" },
{ name: "Suspicioni", img: "suspicioni.png" },
{ name: "Tantroni", img: "pataletoni.png" },
{ name: "Contrarioni", img: "contrarioni.png" },
{ name: "Tengloom", img: "tengulecto.png" },
{ name: "Nird", img: "tengullon.png" },
{ name: "Negasus", img: "negasus.png" },
{ name: "Neighfarious", img: "pifiasus.png" },
{ name: "Timidevil", img: "timidiablo.png" },
{ name: "Beelzebold", img: "osademonio.png" },
{ name: "Count Cavity", img: "conde_caries.png" },
{ name: "Greesel", img: "avarqueroso.png" },
{ name: "Awevil", img: "diables.png" },
{ name: "Coughkoff", img: "ejemtos.png" },
{ name: "Hurchin", img: "erizlor.png" },
{ name: "Peckpocket", img: "cartepollo.png" },
{ name: "Rockabelly", img: "rafaz.png" },
{ name: "Buhu", img: "ayay.png" },
{ name: "Flumpy", img: "horterraro.png" },
{ name: "Skreek", img: "alarcion.png" },
{ name: "Manjimutt", img: "cantonio.png" },
{ name: "Multimutt", img: "multiniche.png" },
{ name: "Sir Berus", img: "ser_bero.png" },
{ name: "Droplette", img: "goto.png" },
{ name: "Drizzle", img: "sirimiri.png" },
{ name: "Slush", img: "copo.png" },
{ name: "Alhail", img: "ventisquero.png" },
{ name: "Gush", img: "coagulon.png" },
{ name: "Chatalie", img: "reboca.png" },
{ name: "Nagatha", img: "pilicajosa.png" },
{ name: "Dismarelda", img: "negatalia.png" },
{ name: "Cheeksqueek", img: "cuesco.png" },
{ name: "Cuttincheez", img: "peditum.png" },
{ name: "Compunzer", img: "graciosno.png" },
{ name: "Lamedian", img: "hilarion.png" },
{ name: "Grumples", img: "arruñona.png" },
{ name: "Everfore", img: "belladona.png" },
{ name: "Eterna", img: "eterna.png" },
{ name: "Insomni", img: "insomna.png" },
{ name: "Sandi", img: "morfea.png" },
{ name: "Noko", img: "noko.png" },
{ name: "Bloominoko", img: "florinoko.png" },
{ name: "Pandanoko", img: "pandanoko.png" },
{ name: "Heheheel", img: "anjijila.png" },
{ name: "Croonger", img: "tenongrio.png" },
{ name: "Urnaconda", img: "urnaconda.png" },
{ name: "Fishpicable", img: "pezqueroso.png" },
{ name: "Rageon", img: "pezgativo.png" },
{ name: "Tunatic", img: "pezquiciado.png" },
{ name: "Draggie", img: "draqui.png" },
{ name: "Dragon Lord", img: "lord_dragon.png" },
{ name: "Azure Dragon", img: "dragon_azur.png" },
{ name: "Daiz", img: "ido.png" },
{ name: "Confuze", img: "turdido.png" },
{ name: "Chummer", img: "pelluron.png" },
{ name: "Shrook", img: "pringuron.png" },
{ name: "Spenp", img: "boquirroto.png" },
{ name: "Almi", img: "yopago.png" },
{ name: "Babblong", img: "charlaton.png" },
{ name: "Bananose", img: "tochaplatano.png" },
{ name: "Copperled", img: "mandicoro.png" },
{ name: "Cynake", img: "ciniserpe.png" },
{ name: "Slitheref", img: "arfidio.png" },
{ name: "Venoct", img: "venocto.png" },
{ name: "Shadow Venoct", aliases: ["Shadow Venoct", "Shad. Venoct", "Shad Venoct"], img: "venoctoscuro.png" },
{ name: "Shogunyan", img: "shogunyan.png" },
{ name: "Komashura", img: "komasura.png" },
{ name: "Dandoodle", img: "dandiniche.png" },
{ name: "Elder Bloom", img: "abuflorido.png" },
{ name: "Gilgaros", img: "dorantuo.png" },
{ name: "Sapphinyan", img: "zafinyan.png" },
{ name: "Emenyan", img: "esmenyan.png" },
{ name: "Rubinyan", img: "rubinyan.png" },
{ name: "Topanyan", img: "topanyan.png" },
{ name: "Dianyan", img: "diamanyan.png" },
{ name: "Slimamander", img: "babamandra.png" },
{ name: "Sproink", img: "termascino.png" },
{ name: "SV Snaggerjag", img: "bergantin.png" },
{ name: "Massiface", img: "animanstruo.png" },
{ name: "Phantasmurai", img: "fantasmurai.png" },
{ name: "Tarantutor", img: "tarantutor.png" },
{ name: "Dr. Maddiman", aliases: ["dr. maddiman", "dr maddiman", "doctor maddiman"], img: "dr._majarov.png" },
{ name: "McKraken", img: "mckraken.png" },
{ name: "McKraken", img: "mckraken_2.png" },
{ name: "Duwheel", img: "duoleta.png" },
{ name: "Chirpster", img: "cantaderna.png" },
{ name: "Eyedra", img: "ojimandra.png" },
{ name: "Hoggles", img: "jabalupo.png" },
{ name: "Styx Mk.VI", aliases: ["Styx Mk.VI", "Styx Mk. VI", "Styx Mk VI"], img: "estigio_vi.png" },
{ name: "Clipso", img: "clipso.png" },
{ name: "Dr. Nogut", aliases: ["dr. nogut", "dr nogut", "doctor nogut"], img: "dr._sintripas.png" },
{ name: "Spooklunk", img: "terrormadura.png" },
{ name: "Squisker", img: "calarrupto.png" },
{ name: "Wobblewok", img: "caldewok.png" },
{ name: "Gargaros", img: "gargantuo.png" },
{ name: "Ogralus", img: "cazamentires.png" },
{ name: "Orcanos", img: "demoniorco.png" },
 { name: "Brushido", img: "Milimpiano.png" },
    { name: "Washogun", img: "Samulimpio.png" },
    { name: "Lie-in", img: "Dormileon.png" },
    { name: "Lie-in Heart", img: "Leon_Alfa.png" },
    { name: "Hissfit", img: "Pataleto.png" },
    { name: "Tublappa", img: "Chupatinas.png" },
    { name: "Slicenrice", img: "Cortarroz.png" },
    { name: "Flamurice", img: "Socarrat.png" },
    { name: "Mudmunch", img: "Atierrador.png" },
    { name: "Sgt. Burly", aliases: ["Sgt. Burly", "Sgt Burly", "Sergeant Burly"], img: "Capi-cachas.png" },
    { name: "Demuncher", img: "Devoramonios.png" },
    { name: "Devourer", img: "Devoralmas.png" },
    { name: "Brokenbrella", img: "Fracaguas.png" },
    { name: "Pittapatt", img: "Chancleto.png" },
    { name: "Houzzat", img: "Komecasa.png" },
    { name: "Faysoff", img: "Sincara.png" },
    { name: "So-Sorree", img: "Losiento.png" },
    { name: "Bowminos", img: "Domiplof.png" },
    { name: "Smogling", img: "Niebli.png" },
    { name: "Smogmella", img: "Nebula.png" },
    { name: "Master Oden", img: "Don_Kaldo.png" },
    { name: "Failian", img: "Falsillo.png" },
    { name: "Apelican", img: "Apelicano.png" },
    { name: "Miradox", img: "Trielespejo.png" },
    { name: "Verygoodsir", img: "Ambrosio.png" },
    { name: "Chymera", img: "Kimera.png" },
    { name: "Kingmera", img: "Kimerreal.png" },
    { name: "Terrorpotta", img: "Aterracota.png" },
    { name: "Wotchagot", img: "Quierodeso.png" },
    { name: "Pride Shrimp", img: "Gambulloso.png" },
    { name: "No-Go Kart", img: "Indiligencio.png" },
    { name: "Mistank", img: "Tanquivocado.png" },
    { name: "Mimikin", img: "Mimoniqui.png" },
    { name: "Enduriphant", img: "Mamuguanto.png" },
    { name: "Zappary", img: "Rayael.png" },
    { name: "Frazzel", img: "Cazarrayos.png" },
    { name: "Swelton", img: "Zudado.png" },
    { name: "Toadal Dude", img: "Eleganfibio.png" },
    { name: "Uber Geeko", img: "Frikigarto.png" },
    { name: "Leggly", img: "Patis.png" },
    { name: "Jumbelina", img: "Picassina.png" },
    { name: "Boyclops", img: "Chiclope.png" },
    { name: "Buchinyan", img: "Buchinyan.png" },
    { name: "Bakulia", img: "Somnia.png" },
    { name: "Drizzelda", img: "Cellisca.png" },
    { name: "Nekidspeed", img: "Rapidizo.png" },
    { name: "Harry Barry", img: "Oso_Boco.png" },
    { name: "Faux Kappa", img: "Kappafalso.png" },
    { name: "Tigappa", img: "Tigrappa.png" },
    { name: "Master Nyada", img: "Gran_Mangu.png" },
    { name: "Kelpacabana", img: "Algacabana.png" },
    { name: "Tongus", img: "Niscala.png" },
    { name: "Nurse Tongus", img: "Curaniscala.png" },
    { name: "Sandmeh", img: "Arenito.png" },
    { name: "Mr. Sandmeh", aliases: ["Mr. Sandmeh", "Mr Sandmeh", "Mister Sandmeh"], img: "Don_Arenito.png" },
    { name: "Pallysol", img: "Sombrillo.png" },
    { name: "Scarasol", img: "Sombrillogro.png" },
    { name: "Supoor Hero", img: "Pauperman.png" },
    { name: "Gnomey", img: "Nomi.png" },
    { name: "High Gnomey", img: "Gran_Nomi.png" },
    { name: "Predictabull", img: "Torivinador.png" },
    { name: "Smashibull", img: "Torivino.png" },
    { name: "DON-CHAN", aliases: ["DON-CHAN", "Don chan"], img: "Don-chan.png" },
    { name: "Ray O'Light", aliases: ["Ray O'Light", "Ray O' Light", "Ray O Light"], img: "Rayito.png" },
    { name: "Kyryn", img: "Kyryn.png" },
    { name: "Unikirin", img: "Unikyryn.png" },
    { name: "Wydeawake", img: "Envelo.png" },
    { name: "Allnyta", img: "Cafeino.png" },
    { name: "Herbiboy", img: "Acelgo.png" },
    { name: "Carniboy", img: "Morenaso.png" },
    { name: "Yoink", img: "Prestragon.png" },
    { name: "Gimme", img: "Bolsadron.png" },
    { name: "K'mon-K'mon", img: "Espaoi.png" },
    { name: "Yoodooit", img: "Hazlotu.png" },
    { name: "Count Zapaway", img: "Zappingla.png" },
    { name: "Tyrat", img: "Rataleza.png" },
    { name: "Snobetty", img: "Frivolia.png" },
    { name: "Slimamander", img: "Babamandra_A.png" },
    { name: "Dracunyan", img: "Dracunyan.png" },
    { name: "Eyesoar", img: "Ojezno.png" },
    { name: "Eyellure", img: "Joyezno.png" },
    { name: "Wobblewok", img: "Caldewok_A.png" },
    { name: "Robbinyu", img: "Mirlobirlo.png" },
    { name: "Squeeky", img: "Estrequito.png" },
    { name: "Rawry", img: "Vrumbo.png" },
    { name: "Furgus", img: "Peluco.png" },
    { name: "Furdinand", img: "Foliculio.png" },
    { name: "Nosirs", img: "No-no.png" },
    { name: "Papa Windbag", img: "Batallitos.png" },
    { name: "Ben Tover", img: "Eskakeo.png" },
    { name: "Toiletta", img: "Lena.png" },
    { name: "Foiletta", img: "Malena.png" },
    { name: "Sproink", img: "Termascino_A.png" },
    { name: "Arachnus", img: "Aracnio.png" },
    { name: "Arachnia", img: "Aracne.png" },
    { name: "Cricky", img: "Torticolis.png" },
    { name: "Snaggly", img: "Malmet.png" },
    { name: "Whinona", img: "Agorerana.png" },
    { name: "Flushback", img: "Desolvidador.png" },
    { name: "Vacuumory", img: "Memorio.png" },
    { name: "Irewig", img: "Mosquereta.png" },
    { name: "Firewig", img: "Bronquereta.png" },
    { name: "Mermaidyn", img: "Nereida.png" },
    { name: "Mermadonna", img: "Sirenia.png" },
    { name: "Mermother", img: "Oceanida.png" },
    { name: "Lady Longnek", img: "Cisnia.png" },
    { name: "Draaagin", img: "Vacilagon.png" },
    { name: "SV Snaggerjag", img: "Bergantin_A.png" },
    { name: "Spoilerina", img: "Chafarina.png" },
    { name: "Poofessor", img: "Repeloso.png" },
    { name: "Slurpent", img: "Octosierpe.png" },
    { name: "Melonyan", img: "Melonyan.png" },
    { name: "Oranyan", img: "Naranyan.png" },
    { name: "Kiwinyan", img: "Kiwinyan.png" },
    { name: "Grapenyan", img: "Uvanyan.png" },
    { name: "Strawbnyan", img: "Fresanyan.png" },
    { name: "Watermelnyan", img: "Sandinyan.png" },
    { name: "Robokapp", img: "Robokapp.png" },
    { name: "Robokoma", img: "Robokoma.png" },
    { name: "Robogramps", img: "Roboabuzampa.png" },
    { name: "Robomutt", img: "Robocantonio.png" },
    { name: "Robonoko", img: "Robonoko.png" },
    { name: "Robodraggie", img: "Robodraqui.png" },
    { name: "Wondernyan", img: "Maravinyan.png" },
    { name: "Robonyan F", img: "Robonyan_2.0.png" },
    { name: "Sailornyan", img: "Sailornyan.png" },
    { name: "Machonyan", img: "Tigrenyan.png" },
    { name: "Hovernyan", img: "Hovernyan.png" },
    { name: "Darknyan", img: "Darknyan.png" },
    { name: "Jibakoma", img: "Jibakoma.png" },
    { name: "Jetnyan", img: "Jetnyan.png" },
    { name: "Unfairy", img: "Injustio.png" },
    { name: "Unkaind", img: "Malicia.png" },
    { name: "Untidy", img: "Implacablio.png" },
    { name: "Unpleasant", img: "Inaguantablio.png" },
    { name: "Unkeen", img: "Destrukto.png" },
    { name: "Grublappa", img: "Chupatodo.png" },
    { name: "Madmunch", img: "Atierrahorror.png" },
    { name: "Badsmella", img: "Apestula.png" },
    { name: "Mad Kappa", img: "Kappamalo.png" },
    { name: "Shamasol", img: "Sombrio.png" },
    { name: "Gnomine", img: "Pillastre.png" },
    { name: "Defectabull", img: "Toragorero.png" },
    { name: "Feargus", img: "Cardado.png" },
    { name: "Scaremaiden", img: "Trampeida.png" },
    { name: "Wrongnek", img: "Malisnia.png" },
    { name: "Grumpus Khan", img: "Keji_Do_Khan.png" },
    { name: "Groupus Khan", img: "Gruñon_Khan.png" },
    { name: "Slumberhog", img: "Puergazan.png" },
    { name: "Snortlehog", img: "Torreznio.png" },
    { name: "Panja Pupil", img: "Pupilo_Panja.png" },
    { name: "Panja Pro", img: "Panja_Pro.png" },
    { name: "Samureel", img: "Samuranguila.png" },
    { name: "Time Keeler", img: "Anguilocio.png" },
    { name: "Takoyakid", img: "Minipulpobola.png" },
    { name: "Takoyaking", img: "Pulpobola_Rey.png" },
    { name: "Danke Sand", img: "Aranecido.png" },
    { name: "No Sandkyu", img: "Desaranecido.png" },
    { name: "Sumodon", img: "Sumodon.png" },
    { name: "Yokozudon", img: "Supersumodon.png" },
    { name: "Whateverest", img: "Desinverest.png" },
    { name: "Whatuption", img: "Inverestupcion.png" },
    { name: "Happycane", img: "Contentallo.png" },
    { name: "Starrycane", img: "Talloestrella.png" },
    { name: "Gutsy Bones", img: "Tripasqueleto.png" },
    { name: "Meganyan", img: "Meganyan.png" },
    { name: "Cap'n Crash", aliases: ["Cap'n Crash", "Captain Crash"], img: "Capitan_Penas.png" },
    { name: "Eyeclone", img: "Cicluracan.png" },
    { name: "Kin", img: "Aurea.png" },
    { name: "Gin", img: "Argenta.png" },
    { name: "Dame Dedtime", img: "Lady_Desdicha.png" },
    { name: "Dame Demona", img: "Lady_Demona.png" },
    { name: "Hans Full", img: "Manojo.png" },
    { name: "Eyephoon", img: "Torbelloptico.png" },
    { name: "Mallice", img: "Martillete.png" },
    { name: "Cap'n Rex", aliases: ["Cap'n Rex", "Captain Rex"], img: "Capipalante.png" },
    { name: "Flippa", img: "Pili.png" },
    { name: "Floppa", img: "Mili.png" },
    { name: "Dame Dredful", img: "Lady_Espanto.png" },
    { name: "Kat Kraydel", img: "Kali_Mera.png" },
    { name: "Goldy Bones", img: "Aureosqueleto.png" },
    { name: "Glitzy Bones", img: "Diamanqueleto.png" },
    { name: "Hans Galore", img: "Manazas.png" },
    { name: "Retinado", img: "Retinado.png" },
    { name: "Snottle", img: "Tomoko.png" },
    { name: "Moximous N", img: "Ultra_N.png" },
    { name: "Moximous K", img: "Ultra_K.png" },
    { name: "Jibanyan S", img: "Jibanyan_S.png" },
    { name: "Komasan S", img: "Komasan_S.png" },
    { name: "Komajiro S", img: "Komajiro_S.png" },
    { name: "Darkyubi", img: "Oskyubi.png" },
    { name: "Illuminoct", img: "Iluminocto.png" },
    { name: "Gargaros", img: "Gargantuo_A.png" },
    { name: "Ogralus", img: "Cazamentires_A.png" },
    { name: "Orcanos", img: "Demoniorco_A.png" },
    { name: "Rubeus J", img: "Rubeo_J.png" },
    { name: "Hardy Hound", img: "Gran_Sabueso.png" },
    { name: "Hinozall", img: "Intelecto.png" },
    { name: "Bronzlow", img: "Nulo.png" },
    { name: "Teastroyer", img: "Testructor.png" },
    { name: "Infinipea", img: "Infinitio.png" },
    { name: "Headasteam", img: "Expresso.png" },
    { name: "Kabuking", img: "Kabukio.png" },
    { "name": "Rudy", "img": "Pelirrojo.png" },
  { "name": "Blizzie", "img": "Grazi.png" },
  { "name": "Usapyon", "img": "Usapyon.png" },
  { "name": "Usapyon", "img": "Usapyon_F.png" },
  { "name": "Usapyon", "img": "Usapyon_S.png" },
  { "name": "Usapyon", "img": "Usapyon_M.png" },
  { "name": "Usapyon", "img": "Usapyon_P.png" },
  { "name": "Whisper", "img": "Whisper.png" },
  { "name": "Whispocrates", aliases: ["Whispocrates", "Private Whispocrates"], "img": "Whispocrates.png" },
  { "name": "Jibanyan B", "img": "Jibanyan_B.png" },
  { "name": "Komasan B", "img": "Komasan_B.png" },
  { "name": "Sir Nyansalot", "img": "Sir_Nyancelot.png" },
  { "name": "Maginyan", "img": "Maginyan.png" },
  { "name": "Momonyan", "img": "Momonyan.png" },
  { "name": "Puppynyan", "img": "Perronyan.png" },
  { "name": "Chimpanyan", "img": "Simionyan.png" },
  { "name": "Pheasanyan", "img": "Faisanyan.png" },
  { "name": "Demuncher", "img": "Devoramonios_B.png" },
  { "name": "Devourer", "img": "Devoralmas_B.png" },
  { "name": "Tattleterror", "img": "Cotiterror.png" },
  { "name": "Mass Mutterer", "img": "Murmullamasa.png" },
  { "name": "Whisped Cream", aliases: ["Whisped Cream", "Whismellowman"], "img": "Cremaligno.png" },
  { "name": "Robonyan 28", "img": "Robonyan_28.png" },
  { "name": "Red Paws", "img": "Zarparroja.png" },
  { "name": "Swirlious Omai", "img": "Vueltomai.png" },
  { "name": "Bison Burly", "img": "Coman-cachas.png" },
  { "name": "Arachnevil", "img": "Aracnefico.png" },
  { "name": "Toadal Demon", "img": "Belcefibio.png" },
  { "name": "Fuu 2", "img": "Normalino.png" },
  { "name": "Kintaronyan", "img": "Kintaronyan.png" },
  { "name": "Kabuking", "img": "Kabukio_A.png" },
  { "name": "Rubeus J", "img": "Rubeo_J_A.png" },
  { "name": "Hardy Hound", "img": "Gran_Sabueso_A.png" },
  { "name": "Seaweed Sns.", aliases: ["Seaweed Sns.", "Seaweed Sensei"],  "img": "Alga_Sensei.png" },
  { "name": "Odysseynyan", "img": "Odisenyan.png" },
  { "name": "Gutsy Bones", "img": "Tripasqueleto_A.png" },
  { "name": "Usapyon B", "img": "Usapyon_B.png" },
  { "name": "Drenchetta", "img": "Tristeresa.png" },
  { "name": "Starry Noko", "img": "Estrenoko.png" },
  { "name": "Lord Enma", "img": "Gran_Enma.png" },
  { "name": "Captain Thunder", "img": "Capitan_Rayo.png" },
  { "name": "Captain Thunder", "img": "Capitan_Rayo_S.png" },
  { "name": "Robonyan 3000", "img": "Robonyan_3000.png" },
  { "name": "Duke Drooly", "img": "Duque_Lametodo.png" },
  { "name": "Alicktokat", "img": "Chupatricio.png" },
  { "name": "Zazel", "img": "Zazel.png" },
  { "name": "Zazelmare", "img": "Zazerilio.png" },
  { "name": "Golden Claws", "img": "Zarpadorada.png" },
  { "name": "Swirlious Gold", "img": "Vueltodorado.png" },
  { "name": "Hinozall Awoken", "img": "Intelecto_Iluminado.png" },
  { "name": "Shogun King", "img": "Shogun_Real.png" },
  { "name": "Pink Emperor", "img": "Emperador_Rosa.png" },
{ "name": "Sigh-Durr", "img": "Robin_Ful.png" },
  { "name": "Flippit", "img": "Tornalmohado.png" },
  { "name": "Brutle", "img": "Gran_Coco.png" },
  { "name": "Minimoto", "img": "Minimoto.png" },
  { "name": "Goofball", "img": "Bola_Blanda.png" },
  { "name": "Slugger", "img": "Bateados.png" },
  { "name": "Lappinitup", "img": "Chupapremios.png" },
  { "name": "El Gutso", "img": "Guerrero_Guey.png" },
  { "name": "El Gutso Grande", "img": "Huracan_Guey.png" },
  { "name": "BBQvil", "img": "Barbacoo.png" },
  { "name": "Liarbird", "img": "Piopio_Yonohesido.png" },
  { "name": "Hot Air Buffoon", "img": "Globonauta.png" },
  { "name": "Shurikenny", "img": "Shurikenny.png" },
  { "name": "Nunchucky", "img": "Nunchucky.png" },
  { "name": "Camellia", "img": "Camelia.png" },
  { "name": "Zip Unlock", "img": "Cremallero.png" },
  { "name": "Slippup", "img": "Metepatas.png" },
  { "name": "Who-Me", "img": "Mochueloque.png" },
  { "name": "Too-Much-Too-Take", "img": "Todoidos.png" },
  { "name": "Why Naant", "img": "Preguntio.png" },
  { "name": "Naandhi", "img": "Respondio.png" },
  { "name": "Legsit", "img": "Exitio.png" },
  { "name": "Chicken Chukket", "img": "Cachocarne.png" },
  { "name": "Cornfused", "img": "Mazorco.png" },
  { "name": "Unshelltered", "img": "Cascarito.png" },
  { "name": "Lord Shrillington", "img": "Pomponio_Gala.png" },
  { "name": "House Partay", "img": "Fiestuki.png" },
  { "name": "Skulleidoscope", "img": "Calaveroscopio.png" },
  { "name": "Lionguist", "img": "Leonguista.png" },
  { "name": "Statikid", "img": "Estatinino.png" },
  { "name": "Professor Plumage", "img": "Profesor_Avertijo.png" },
  { "name": "Throne Wiper", "img": "Noaipapel.png" },
  { "name": "Imagenius", "img": "Jipigenio.png" },
  { "name": "Miss Teri", "img": "Miss_Teria.png" },
  { "name": "Squandeer", "img": "Renaldo.png" },
  { "name": "Thurston", "img": "Isotomas.png" },
  { "name": "Agent Spect-hare", "img": "Coneagente.png" },
  { "name": "Snow Spect-hare", "img": "Blancacone.png" },
  { "name": "Oh Wheel", "img": "Prudencio.png" },
  { "name": "Blownhistoppa", "img": "Explotacota.png" },
  { "name": "Roughraff", "img": "Grafilcebu.png" },
  { "name": "Chilled Cowcao", "img": "Chocovaca.png" },
  { "name": "Stircrazy Stu", "img": "Vacaloca.png" },
  { "name": "Nummskull", "img": "Fracalavero.png" },
  { "name": "Skillskull", "img": "Calabilidoso.png" },
  { "name": "Oh Bah Gah!", "img": "Master_Chof.png" },
  { "name": "Speedemountain", "img": "Monte_Merario.png" },
  { "name": "Shipshape Sailor", "img": "Calmarinero.png" },
  { "name": "Admirable Admiral", "img": "Almirante_Admirable.png" },
  { "name": "Sing Kong", "img": "Peter_Punki.png" },
  { "name": "Slippy", "img": "Pantuflo.png" },
  { "name": "Repossessor", "img": "Reahucio.png" },
  { "name": "Mr. Blockhead", aliases: ["Mr. Blockhead", "Mr Blockhead"], "img": "Radiopatio.png" },
  { "name": "Steaking", "img": "Filete_II.png" },
  { "name": "Showbonyan", "img": "Showbonyan.png" },
  { "name": "The Jawsome Kid", "img": "Tiburon_Tiburcio.png" },
  { "name": "El Sharkador", "img": "Tiburon_Jaqueton.png" },
  { "name": "Silver Lining", "img": "Capitan_Nublo.png" },
  { "name": "Twirly Pie", "img": "Sincopollo.png" },
  { "name": "Petty-Cake", "img": "Brownilda.png" },
  { "name": "Hoppy-go-Lucky", "img": "Chapulin.png" },
  { "name": "Buttered Blue", "img": "Apanleado.png" },
  { "name": "Punching Baguette", "img": "Panduro.png" },
  { "name": "Unbelievaboy!", "img": "Superninato.png" },
  { "name": "Unbearaboy!", "img": "Superninato_Rebelde.png" },
  { "name": "Inflammaboy!", "img": "Superninato_Picajoso.png" },
  { "name": "Krystal Fox", "img": "BellonZ.png" },
  { "name": "Runsure", "img": "Olvirunner.png" },
  { "name": "Kittylumbus", "img": "Gatallanes.png" },
  { "name": "Zest-a-Minute", "img": "Limonescente.png" },
  { "name": "Cue-Tee", "img": "Tomanota.png" },
  { "name": "Demandi", "img": "Zalameria.png" },
  { "name": "Jibanyan Liu Bei", "img": "Jibanyan_Liu_Bei.png" },
  { "name": "Komasan Sun Ce", "img": "Komasan_Sun_Ce.png" },
  { "name": "Stinkeye", "img": "Todoapesta.png" },
  { "name": "Slackoon", "img": "Relapache.png" },
  { "name": "Puppiccino", "img": "Cafechucho.png" },
  { "name": "Ballin", "img": "Partidacio.png" },
  { "name": "Tomnyan", "img": "Tomnyan.png" },
  { "name": "Koma Knomads", "img": "Komaestopistas.png" },
  { "name": "Whirlweasel", "img": "Segadora.png" },
  { "name": "Chocobonyan", "img": "Chocobonyan.png" },
  { "name": "Mooglenyan", "img": "Mogurinyan.png" },
  { "name": "Wobblenyan", "img": "Wobblenyan.png" },
  { "name": "Wibblekoma", "img": "Wibblekoma.png" },
  { "name": "Sushinyan", "img": "Sushinyan.png" },
  { "name": "Tempurasan", "img": "Tempurasan.png" },
  { "name": "Tenguriginal", "img": "Tenguriginal.png" },
  { "name": "Tengulightened", "img": "Angel_Garudian.png" },
  { "name": "Bumblejack", "img": "Lenaciegotxea.png" },
  { "name": "In-Tune", "img": "Chunda_y_Tachunda.png" },
  { "name": "Supersize Gramps", "img": "Abuzampa_XXL.png" },
  { "name": "Lil Blue Bathing Hood", "img": "Albornocita_Azul.png" },
  { "name": "Bubble Beth", "img": "Florentina.png" },
  { "name": "Afronaut", "img": "Afronauta.png" },
  { "name": "Cereal Spiller", "img": "Arrocet.png" },
  { "name": "Tomorrow Gal", "img": "Espe.png" },
  { "name": "Swaycorn", "img": "Bellotieso.png" },
  { "name": "Push Pup", "img": "Clican.png" },
  { "name": "Ponderoo", "img": "Indeciguro.png" },
  { "name": "Tongue-Twister", "img": "Trabalanghi.png" },
  { "name": "Lazy Sundae", "img": "Dormidomingo.png" },
  { "name": "Got It Maid", "img": "Auxiliadora.png" },
  { "name": "Greengramps", "img": "Abuflauta.png" },
  { "name": "Right Brothers", "img": "Gememinencias.png" },
  { "name": "Tattlecakes", "img": "Repostilleja.png" },
  { "name": "Fundango", "img": "Gogonzalo.png" },
  { "name": "Pearly White", "img": "Esmaltina.png" },
  { "name": "Ghostess", "img": "Fantasfitriona.png" },
  { "name": "Double Time", "img": "Sonico.png" },
  { "name": "Sonic Bam", "img": "Supersonico.png" },
  { "name": "Neggplant", "img": "Berenpenas.png" },
  { "name": "Snitchin", "img": "Akusika.png" },
  { "name": "Messyrai", "img": "Leonerai.png" },
  { "name": "Treetter", "img": "Trenditopico.png" },
  { "name": "Retreeter", "img": "Retuiterio.png" },
  { "name": "Salty Bacon", "img": "Panceto.png" },
  { "name": "Indexter", "img": "Bilgatino.png" },
  { "name": "Hack King", "img": "Su_Hackeltad.png" },
  { "name": "DisliKing", "img": "Rey_Pulsivo.png" },
  { "name": "Crook-a-doodle", "img": "Timo_Gallo.png" },
  { "name": "Rocky Badboya", "img": "Rocky_Malrolla.png" },
  { "name": "Injurnalist", "img": "Hierodista.png" },
  { "name": "Misterr Typoo", "img": "Herrato.png" },
  { "name": "Lil Kappa", "img": "MC_Kappa.png" },
  { "name": "Horizontail", "img": "Tumbardillo.png" },
  { "name": "Usapyon Zhongda", "img": "Usapyon_Zhongda.png" },
  { "name": "Dr. E. Raser", aliases: ["Dr. E. Raser", "Dr E Raser"], "img": "Dr_Nihil_Listo.png" },
  { "name": "Dr. Nocturne", aliases: ["Dr. Nocturne", "Dr Nocturne"], "img": "Dr_Nocturnia.png" },
  { "name": "Tut 'n' K'mon", "img": "Espaya.png" },
  { "name": "Tie-red", "img": "Corbapacasa.png" },
  { "name": "Love-Torn", "img": "Cartairada.png" },
  { "name": "Shakey", "img": "Ambivalencio.png" },
  { "name": "Quagmira", "img": "Lapo.png" },
  { "name": "Pergushin", "img": "Dabombo.png" },
  { "name": "Percrushionists", "img": "Los_Bomboledores.png" },
  { "name": "Grubbles", "img": "Amarilia.png" },
  { "name": "Nervous Rex", "img": "Sheriff_Agonio.png" },
  { "name": "Rinsin Repete", "img": "Padefo.png" },
  { "name": "Soloman", "img": "Sololo.png" },
  { "name": "Rhumbastiltskin", "img": "Maracario.png" },
  { "name": "Slax", "img": "Pandalon.png" },
  { "name": "Shedwin", "img": "Peluson.png" },
  { "name": "Glumdango", "img": "Amarguito.png" },
  { "name": "Spewart", "img": "Nauseo.png" },
  { "name": "Decidevible", "img": "Condespotico.png" },
  { "name": "Hairum Scarum", "img": "Flequipilante.png" },
  { "name": "Oridjinn", "img": "Origenio.png" },
  { "name": "Horridjinn", "img": "Horrogenio.png" },
  { "name": "Little Charrmer", "img": "Fulgurilla.png" },
  { "name": "Humtea Jumtea", "img": "Saltetera.png" },
  { "name": "Snailspace", "img": "Don_Despacito.png" },
  { "name": "Putasockinit", "img": "Sierpesado.png" },
  { "name": "Snidewinder", "img": "Cobravil.png" },
  { "name": "OMGator", "img": "Aymadrilo.png" },
  { "name": "Nautaloss", "img": "Naqueperder.png" },
  { "name": "Shellebrity", "img": "Borjamar.png" },
  { "name": "T-Wrecks", "img": "Bebesaurio.png" },
  { "name": "D-Stroy", "img": "Destrozasaurio.png" },
  { "name": "Clodzilla", "img": "Torpesaurio.png" },
  { "name": "Snippity Cricket", "img": "Luigi_Longueras.png" },
  { "name": "Flocktopus", "img": "Pulpopular.png" },
  { "name": "Bitter Batter", "img": "Tentanfadado.png" },
  { "name": "Cocobanana", "img": "Tochacolate.png" },
  { "name": "Ooze Zat", "img": "Sustoleo.png" },
  { "name": "Mython", "img": "Reptozudo.png" },
  { "name": "Frogetmenot", "img": "Saporientador.png" },
  { "name": "Originyan", "img": "originyan.gif" },
  { "name": "Sighborg Y", "img": "Aydroide_Y.png" },
  { "name": "King Jibanyan", "img": "Rey_Jibanyan.png" },
  { "name": "Queen Usapyon", "img": "Reina_Usapyon.png" },
  { "name": "Jackomasan", "img": "Jotamasan.png" },
  { "name": "Komajiro Ten", "img": "Diez_de_Komajiro.png" },
  { "name": "Acenyan", "img": "Asnyan.png" },
  { "name": "Josper", "img": "Whismodin.png" },
  { "name": "Benzaiten", "img": "Benzaiten.png" },
  { "name": "Hotei", "img": "Hotei.png" },
  { "name": "Daikokuten", "img": "Daikokuten.png" },
  { "name": "Ebisu", "img": "Ebisu.png" },
  { "name": "Bishamonten", "img": "Bishamonten.png" },
  { "name": "Columbakat", "img": "Gatobal_Colon.png" },
  { "name": "T. Energison", aliases: ["T. Energison", "T Energison"], "img": "T_Energison.png" },
  { "name": "Starwin", "img": "Darguin.png" },
  { "name": "The Last Nyanmurai", "img": "Ultimo_Nyanmurai.png" },
  { "name": "Koma Star", "img": "Koma_Estrella.png" },
  { "name": "Platinos", "img": "Platinum.png" },
  { "name": "Flash T. Cash", aliases: ["Flash T. Cash", "Flash T Cash"], "img": "Abusplendido.png" },
  { "name": "Re-Q-Perate", "img": "Re-Q-Pera.png" },
  { "name": "Princess Pearl", "img": "Divamarina.png" },
  { "name": "Asura", "img": "Todobelicoso.png" },
  { "name": "Terminyanator", "img": "Terminyanator.png" },
  { "name": "Supernyan", "img": "Supernyan.png" },
  { "name": "Hovernyan S", "img": "Hovernyan_S.png" },
  { "name": "Hovernyan Cao Cao", "img": "Hovernyan_Cao_Cao.png" },
  { "name": "Yoganalisten", "img": "Yoguididacta.png" },
  { "name": "Judgebrick", "img": "Frauduralla.png" },
  { "name": "Urnfulfilled", "img": "Insaciablo.png" },
  { "name": "Sad to the Bone", "img": "Penancio.png" },
  { "name": "Venoctobot", "img": "Venoctobot.png" },
  { "name": "Orcanos Lu Bu", "img": "Demoniorco_Lu_Bu.png" },
  { "name": "Kyubot", "img": "Kyubot.png" },
  { "name": "Ultimate Robonyan", "img": "Robonyan_Definitivo.png" },
  { "name": "Molar Petite", "img": "Topina.png" },
  { "name": "Life-is-Parfait", "img": "Miss_Mousse.png" },
  { "name": "Mee 2", "img": "populina.gif" },
  { "name": "Koalanyan", "img": "Koalanyan.png" },
  { "name": "Jibanyan T", "img": "jibanyan_T.gif" },
  { "name": "Komasan T", "img": "komasan_T.gif" },
  { "name": "Her Eggcelency", "img": "Yemajestad.png" },
  { "name": "Deadcool", "img": "Cicloman.png" },
  { "name": "Sweattuce", "img": "Deporchugo.png" },
  { "name": "Mr. Blue-Shy", aliases: ["Mr. Blue-Shy", "Mr Blue-Shy"], "img": "Timorato_Buendia.png" },
  { "name": "Amplifly", "img": "Maripasada.png" },
  { "name": "Ulteria", "img": "Ulteria.png" },
  { "name": "My-Baaad", "img": "Milperdones.png" },
  { "name": "Sunk'nsoul", "img": "Angustianima.png" },
  { "name": "Crummy Mummy", "img": "Cutremomia.png" },
  { "name": "Kaped Kommander", "img": "Kapman.png" },
  { "name": "Tofupyon", "img": "Tofupyon.png" },
  { "name": "Ed Zoff", "img": "Dex_Capito.png" },
  { "name": "Gorgeous Ambassador", "img": "Embajador_Fabuloso.png" },
  { "name": "Hinozall", "img": "Intelecto_A.png" },
  { "name": "Zazel", "img": "Zazel_A.png" },
  { "name": "Procrastinocchio", "img": "Procrastinocho.png" },
  { "name": "Treasure Pest", "img": "Cofre_Cafre.png" },
  { "name": "Jeanne Ne-Sais-Quoi", "img": "Coco_Masiel.png" },
  { "name": "Whisper Kongming", "img": "Whisper_Kongming.png" },
  { "name": "Jurojin", "img": "Jurojin.png" },
  { "name": "Fukurokuju", "img": "Fukurokuju.png" },
  { "name": "Sarcophacurse", "img": "Maldenotep.png" },
  { "name": "King Deadward", "img": "Rey_Palmiro.png" },
  { "name": "Pandora", "img": "Pandora.png" },
  { "name": "Comic Genieus", "img": "Ingenio.png" },
  { "name": "Bastnetnyan", "img": "Bastenyan.png" },
  { "name": "Komanubis", "img": "Komanubis.png" },
  { "name": "Gabby", "img": "Discursi.png" },
  { "name": "Teducator", "img": "Educoso.png" },
  { "name": "Gentlemutt", "img": "Lord_Pedigri.png" },
  { "name": "City Licker", "img": "Urbasierpe.png" },
  { "name": "Whyvern King", "img": "Pregundragon_Rey.png" },
  { "name": "Righteous Zazel", "img": "Zazel_Justiciero.png" },
  { "name": "Hinozall Awoken", "img": "Intelecto_Iluminado_A.png" },
  { "name": "Ancient Enma", "img": "Enma_Ancestral.png" },
  { "name": "Lord Enma Awoken", "img": "Gran_Enma_Iluminado.png" },
  { "name": "The Boracle", "img": "Rollaculo.png" },
  { "name": "Rampajah", "img": "Maharazas.png" },
  { "name": "Cymbalina", "img": "Cimbalina.png" },
  { "name": "Mumbles", "img": "Masculloso.png" },
  { "name": "Roary", "img": "Vociferio.png" },
  { "name": "Letzbifrenz", "img": "Aviguito_Pio.png" },
  { "name": "Wack o' Lantern", "img": "Frustrolillo.png" },
  { "name": "Moolinda", "img": "Bovida.png" },
  { "name": "Neighthan", "img": "Equinio.png" },
  { "name": "Big Fish", "img": "Pecificador.png" },
  { "name": "Alpina", "img": "Alpina.png" },
  { "name": "Lunie", "img": "Seleno.png" },
  { "name": "KJ", "img": "KJ.png" },
  { "name": "Solar Enma", "img": "Enma_Solar.png" },
  { "name": "Infinite Enma", "img": "Enma_Infinito.png" },
  { "name": "Umbral Enma", "img": "Enma_Umbrio.png" },
  { "name": "Indiana Jaws", "img": "tibu_Jones.gif" },
  { "name": "Shovulcan", "img": "vulcavador.gif" },
  { "name": "Zomboy", "img": "adoleszombi.gif" },
  { "name": "Nyanses II", "img": "nyanses_II.gif" },
  { "name": "Meopatra", "img": "Miopatra.png" },
  { "name": "Fitwit", "img": "mazado_de_la_Calzada.gif" },
  { "name": "El Dorago", "img": "Dradorado.png" },
  { "name": "The Hinix", "img": "Fenixtelecto.png" },
  { "name": "Junkernaut", "img": "Chatarrenstein.png" },
  { "name": "Supermanager", "img": "Supergerente.png" },
  { "name": "Hoaxy-Coaxy", "img": "Ilusionisto.png" },
  { "name": "Agent X", "img": "Camorro.png" },
  { "name": "The Executor", "img": "Diavolo.png" },
  { "name": "Slackerjack", "img": "Flautista_de_Malmelin.png" },
  { "name": "Yo-kaiju", "img": "Gamero.png" },
  { "name": "Yopple-Bot", "img": "Yopple-Bot.png" },
  { "name": "No-Bot", "img": "No-Bot.png" },
  { "name": "Beddy-Byes", "img": "Nocturnia.png" },
  { "name": "Rongo Swirll", "img": "Ray_Baqueto.png" },
  { "name": "The Ghoulfather", "img": "Don_Crueleone.png" },
  { "name": "Don Spiracy", "img": "Don_Conspirazione.png" },
  { "name": "Slackolyte", "img": "Flautiscolito.png" },
  { "name": "Duolyte", "img": "Duocolito.png" },
  { "name": "Chirpolyte", "img": "Cantacolito.png" },
  { "name": "Torneyedo", "img": "Ciclonojo.png" },
  { "name": "Hollow Guard", "img": "Caballero_Hueco.png" },
  { "name": "Skulk", "img": "Paticio.png" },
  { "name": "Orcalyte", "img": "Demoniorcolito.png" },
  { "name": "The Zenlightener", "img": "Iluminazen.png" },
  { "name": "Plundros", "img": "Capitan_Botin.png" },
  { "name": "Yellskitchen", "img": "Chef_Ricote.png" },
  { "name": "Maiden Ruin", "img": "Doncella_de_la_Ruina.png" },
  { "name": "The Woebra", "img": "Necrocobra.png" },
  { "name": "The Goldfather", "img": "Don_Aureone.png" },
  { "name": "IcarOS", "img": "Icarus.png" },
  { "name": "Narwail", "img": "Ballenato.png" },
  { "name": "Whaleman", "img": "Cachaslote.png" },
  { "name": "Soulcleaver", "img": "El_Carnicero.png" },
  { "name": "Holey Moley", "img": "Topoderoso.png" },
  { "name": "The Lastest Nyanmurai", "img": "El_Ultimisimo_Nyanmurai.png" },
 { name: "Ogamitaoshi", img: "Ogamitaoshi.png" },
    { name: "Captain Dodo", img: "Capitan_Dodo.png" },
    { name: "Chousensha", img: "Chosensha.png" },
    { name: "Monomaneking", aliases: ["Monomaneking", "Mimiking"], img: "Monomaneking.png" },
    { name: "Morigami Rex", img: "Morigami_Rex.png" },
    { name: "Wibblejiro", aliases: ["Wibblejiro", "Wobblejiro", "Punijiro"], img: "Wibblejiro.png" },
    { name: "Shourinji", img: "Shourinji.png" },
    { name: "Raise Girl", img: "Raise_Girl.png" },
    { name: "Katenshi", img: "Katenshi.png" },
    { name: "Futekusaru", img: "Futekusaru.png" },
    { name: "Usapyon T", aliases: ["Usapyon T", "T-Usapyon"], img: "Usapyon_T.png" },
    { name: "Maizo Tokugawa", img: "Maizo_Tokugawa.png" },
    { name: "Al Baccino", aliases: ["Al Baccino", "Are Bacchino"], img: "Al_Baccino.png" },
    { name: "Gutsy Bones T", aliases: ["Gutsy Bones T", "Gashadokuro T"], img: "Tripasqueleto_T.png" },
    { name: "Kaneuki-hime", img: "Kaneuki-hime.png" },
    { name: "AkiraMEN", img: "AkiraMEN.png" },
    { name: "Omoutsubo", img: "Omoutsubo.png" },
    { name: "Naga Raja", img: "Naga_Raja.png" },
    { name: "Doyagari Tribe", aliases: ["Doyagari Tribe", "Doyagari-zoku"], img: "Tribu_Doyagari.png" },
    { name: "Doya Osa", img: "Doya_Osa.png" },
    { name: "Vascoda Gama", img: "Vascoda_Gama.png" },
    { name: "Crystal SHogunyan", img: "Shogunyan_Cristal.png" },
    { name: "Wobblehover", aliases: ["Wobblehover", "Wibblehover", "Punifuyu"], img: "Wobblehover.png" },
    { name: "Jibanyan T G", aliases: ["Jibanyan T G", "T-Jibanyan G"], img: "Jibanyan_T_G.png" },
    { name: "Jibanyan D", img: "Jibanyan_D.png" },
    { name: "Komasan T G", aliases: ["Komasan T G", "T-Komasan G"], img: "Komasan_T_G.png" },
    { name: "Komasan D", img: "Komasan_D.png" },
    { name: "Indiana Jaws G", aliases: ["Indiana Jaws G", "Indy Jaws G"], img: "Tibu_Jones_G.png" },
    { name: "Cindy Jaws", img: "Cindy_Jaws.png" },
    { name: "Shovulcan G", aliases: ["Shovulcan G", "Mr. Scoop G"], img: "Vulcavador_G.png" },
    { name: "Zomboy G", aliases: ["Zomboy G", "Zom B Chopper G"], img: "Adoleszombi_G.png" },
    { name: "Nyanses II G", aliases: ["Nyanses II G", "Neko II G"], img: "Nyanses_II_G.png" },
    { name: "Yodelsen", img: "Yodelsen.png" },
    { name: "Narcis II", img: "Narciso_II.png" },
    { name: "Zappadokia", img: "Zappadokia.png" },
    { name: "Mademoaiselle", img: "Mademoaiselle.png" },
    { name: "Rosetta Stone", img: "Piedra_Rosetta.png" },
    { name: "Doescalibur", img: "Doescalibur.png" },
    { name: "Encore Dead", img: "Encore_Dead.png" },
    { name: "Armaterasu", aliases: ["Armaterasu", "Armorterasu", "Amaterasu"], img: "Armaterasu.png" },
    { name: "Dandory", img: "Dandory.png" },
    { name: "Spatto", img: "Spatto.png" },
    { name: "Tanto", img: "Tanto.png" },
    { name: "Kirene", img: "Kirene.png" },
    { name: "Toranka", img: "Toranka.png" },
    { name: "Catleen", img: "Catleen.gif" },
    { name: "Gustaf", img: "Gustaf.png" },
    { name: "Gowin", img: "Gowin.png" },
    { name: "Seirei Banbarayar", img: "Seirei_Banbarayar.png" },
    { name: "Enma", img: "Enma.png" },
    { name: "Dark Enma", aliases: ["Dark Enma", "Yami Enma"], img: "Enma_Oscuro.png" },
    { name: "Lord Ananta", img: "Lord_Ananta.png" },
    { name: "Enma Meiou Maka", img: "Enma_Meiou_Maka.png" },
    { name: "Enmanyan", aliases: ["Enmanyan", "Enma Neko'ou Matatabi"], img: "Enmanyan.png" },
    { name: "Enma Ryuuou Mizuchi", img: "Enma_Ryuuou_Mizuchi.png" },
    { name: "Enma Raou Tekakku", img: "Enma_Raou_Tekakku.png" },
    { name: "Lord Acala", img: "Lord_Acala.png" },
    { name: "Chi Ma Tree", img: "Chi_Ma_Tree.png" },
    { name: "BaiKING", img: "BaiKING.png" },
    { name: "Boogiemum", img: "Boogiemum.png" },
    { name: "Kanibouzu", img: "Kanibouzu.png" },
    { name: "Orifalcon", img: "Orifalcon.png" },
    { name: "WaNEWdo", img: "WaNEWdo.png" },
    { name: "Dark Master", img: "Dark_Master.png" },
    { name: "Wandering Billy", aliases: ["Wandering Billy", "Sasurai no Billy"], img: "Billy_el_Errante.png" },
    { name: "Gowin", img: "Gowin_B.png" },
    { name: "Kanaendesu", img: "Kanaendesu.png" },
    { name: "Majin Banbarayar", img: "Majin_Banbarayar.png" },
    { name: "Yodelsen", img: "Yodelsen_B.png" },
    { name: "Zircondor", img: "Zircondor.png" },
     { "name": "Jabow", "img": "Jabow.png" },
  { "name": "Shirokuma", "img": "Shirokuma.png" },
  { "name": "Punkupine", "img": "Punkupine.png" },
  { "name": "Sorrypus", "img": "Sorrypus.png" },
  { "name": "McKraken", "img": "McKraken.png" },
  { "name": "Hungramps", "img": "Abuzampa.gif" },
  { "name": "Pakkun", aliases: ["Pakkun", "Gabriel"], "img": "Pakkun.gif" },
  { "name": "Kyunshii", aliases: ["Kyunshii", "Zukkyunshii"], "img": "Kyunshii.gif" },
  { "name": "Hare-onna", aliases: ["Hare-onna", "Ame-onna"], "img": "Hare-onna.gif" },
  { "name": "Kakurenbou", aliases: ["Kakerenbou", "Inaiinaibaa"], "img": "Kakurenbou.gif" },
  { "name": "Blizzaria", "img": "Granizia.gif" },
  { "name": "Damona", "img": "Damona.gif" },
  { "name": "Zazel", "img": "Zazel_2040.png" },
  { "name": "Daniel", aliases: ["Daniel", "Big Danny"], "img": "Daniel.gif" },
  { "name": "Choky", aliases: ["Choky", "Shiomaneki"], "img": "Choky.gif" },
  { "name": "Blazion", "img": "Flamileon.gif" },
  { "name": "Itashikatanashi", aliases: ["Itashikatanashi", "Yamuwoen"], "img": "Itashikatanashi.gif" },
  { "name": "Saya", aliases: ["Saya", "Makenki"], "img": "Saya.gif" },
  { "name": "Papa Bolt", "img": "Papa_Rayo.gif" },
  { "name": "Venoct", "img": "Venocto.gif" },
  { "name": "Shadow Venoct", "img": "Venoctoscuro.gif" },
  { "name": "Shogunyan", "img": "Shogunyan.gif" },
  { "name": "Komashura", "img": "Komasura.gif" },
  { "name": "Arachnus", "img": "Aracnio.gif" },
  { "name": "Lil' Acala", aliases: ["Lil' Acala", "Lil Acala"], "img": "Lil'_Acala.png" },
  { "name": "Honmaguro-taisho", aliases: ["Honmaguro-taisho", "Magulodon", "Neptuna"], "img": "Honmaguro-taisho.gif" },
  { "name": "Semicolon", aliases: ["Semicolon", "Semirongu", "Bugaboo"], "img": "Semicolon.gif" },
  { "name": "Komasan", "img": "Komasan.gif" },
  { "name": "Komajiro", "img": "Komajiro.gif" },
  { "name": "Banchou", aliases: ["Banchou", "Bourei Banchou", "Basher"], "img": "Banchou.gif" },
  { "name": "Noko", "img": "Noko.gif" },
  { "name": "Azure Dragon", "img": "Dragon_Azur.gif" },
  { "name": "Fuu-kun", aliases: ["Fuu-kun", "Fuujin"], "img": "Fuu-kun.gif" },
  { "name": "Rai-chan", aliases: ["Rai-chan", "Raijin"], "img": "Rai-chan.gif" },
  { "name": "Toadal Dude", "img": "Eleganfibio.gif" },
  { "name": "Jibanyan", "img": "Jibanyan.gif" },
  { "name": "Uribou", aliases: ["Uribou", "Inosasaou"], "img": "Uribou.gif" },
  { "name": "Hamham", aliases: ["Hamham", "Abraham"], "img": "Hamham.gif" },
  { "name": "Doyapon", aliases: ["Doyapon", "Doudanuki"], "img": "Doyapon.gif" },
  { "name": "Kyubi", "img": "Kyubi.gif" },
  { "name": "Frostail", "img": "Nievacolas.gif" },
  { "name": "Charlie", aliases: ["Charlie", "Ghostcycle"],  "img": "Charlie.gif" },
  { "name": "Kezurin", aliases: ["Kezurin", "Jinkotsukezuri"], "img": "Kezurin.gif" },
  { "name": "Hot Pot", aliases: ["Hot Pot", "Zundoumaru", "Shiryou no Dokudoku-nabe"], "img": "Hot_Pot.gif" },
  { "name": "Mirapo", "img": "Telespejo.gif" },
  { "name": "Jinta", aliases: ["Jinta", "Jingeki"], "img": "Jinta.gif" },
  { "name": "Kantaro", aliases: ["Kantaro", "Jihanki"], "img": "Kantaro.gif" },
  { "name": "Tidynator", aliases: ["Tidynator", "Robonyan 00"], "img": "Tidynator.gif" },
  { "name": "Kiborikkuma", aliases: ["Kiborikkuma", "Onikuma"], "img": "Kiborikkuma.gif" },
  { "name": "Junior", aliases: ["Junior", "Burning Dragon"], "img": "Junior.gif" },
  { "name": "Whisper", "img": "Whisper_2024.png" },
  { "name": "Sly", aliases: ["Sly", "Slimamander", "Super Sly", "Mitsumata Ghidorah"], "img": "Sly.gif" },
  { "name": "Becchan", aliases: ["Becchan", "Nuttarabeccha"], "img": "Becchan.gif" },
  { "name": "Dameboy", aliases: ["Dameboy", "Zettai Guardman"], "img": "Dameboy.gif" },
  { "name": "Fukurou", "img": "Fukurou.png" },
  { "name": "Hinozall", "img": "Intelecto.gif" },
  { "name": "Ogu Togu Mogu", aliases: ["Ogu Togu Mogu", "Ogu, Togu and Mogu", "Ogu, Togu & Mogu"], "img": "Ogu_Togu_Mogu.png" },
  { "name": "Voidera", "img": "Voidera.png" },
  { "name": "Shutendouji", aliases: ["Shutendouji", "Isotomas"], "img": "Shutendouji.png" },
  { "name": "Juno", "img": "Juno.png" },
  { "name": "Boreas", "img": "Boreas.png" },
  { "name": "Eurus", "img": "Eurus.png" },
  { "name": "Saros", "img": "Saros.png" },
  { "name": "Demon Enma", aliases: ["Demon Enma", "Yasha Enma", "Enma Awoken", "Kakusei Enma"], "img": "Yasha_Enma.gif" },
  { "name": "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa.png" },
  { "name": "Kenshin Amaterasu", aliases: ["Kenshin Amaterasu", "Amaterasu"], "img": "Kenshin_Amaterasu.png" },
  { "name": "Suu-san", "img": "Suu-san.png" },
  { "name": "Gnomey", aliases: ["Gnomey", "Zashiki-warashi", "Tengu'ou Kurama"], "img": "Gnomey.gif" },
  { "name": "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa_LS.png" },
  { "name": "Kukuri-hime", "img": "Kukuri-hime.png" },
  { "name": "Gesshin Tsukuyomi", aliases: ["Gesshin Tsukuyomi", "Tsukuyomi"], "img": "Gesshin_Tsukuyomi.png" },
  { "name": "Gusto", aliases: ["Gusto", "Kaibyou Kamaitachi", "Neko'ou Bastet"], "img": "Gusto.gif" },
  { "name": "Kawauso", "img": "Kawauso.png" },
  { "name": "Tamamo", aliases: ["Tamamo", "Tamamo-no-mae"], "img": "Tamamo.gif" },
  { "name": "Gyuuki", "img": "Gyuuki.png" },
  { "name": "Narigama", "img": "Narigama.png" },
  { "name": "Blobgoblin", "img": "Blobgoblin.png" },
  { "name": "Azukiarai", "img": "Azukiarai.png" },
  { "name": "Kappa", aliases: ["Kappa", "Kappa'ou Sagojou"], "img": "Kappa.gif" },
  { "name": "Shien", "img": "Shien.png" },
  { "name": "Lord Enma Gouen", aliases: ["Lord Enma Gouen", "Lord Enma", "Enma Daiou"], "img": "Gran_Enma_Gouen.png" },
  { "name": "Naviwan", "img": "Naviwan.png" },
  { "name": "Konsaru", "img": "Konsaru.png" },
  { "name": "Drone", "img": "Dron.png" },
  { "name": "Alien", aliases: ["Alien", "Mikakunin"], "img": "Miembro_Mikakunin.png" },
  { "name": "Kitaro", "img": "Kitaro.png" },
  { "name": "Papa Eyeball", aliases: ["Papa Eyeball", "Medama Oyaji"], "img": "Papa_Ojo.png" },
  { "name": "Slimamander", "img": "Babamandra_SS.png" },
  { "name": "Medamanbou", aliases: ["Medamanbou", "Slimamander's Eye"], "img": "Medamanbou.png" },    
  { "name": "Jingeki", "img": "Jingeki.png" },
  { "name": "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa_Boss.png" },
  { "name": "Shinmagunshin Fukurou", aliases: ["Shinmagunshin Fukurou", "Corrupt Fukurou"], "img": "Shinmagunshin_Fukurou.png" },
  { "name": "Lady Arachnia", "img": "Lady_Aracne.png" },
  { "name": "Tamamo-no-mae", "img": "Tamamo-no-mae.png" },
  { "name": "Shinma Voidera", aliases: ["Shinma Voidera", "Shinma Douketsu", "Corrupt Voidera"], "img": "Voidera_Boss.png" },
  { "name": "Shien", "img": "Shien.png" },
  { "name": "Shinma Ananta", aliases: ["Shinma Ananta", "Shinma Kaira", "Corrupt Ananta"], "img": "Ananta_Boss.png" },
  { "name": "Overseer", "img": "Overseer.png" },
  { "name": "Maten Overseer", aliases: ["Maten Overseer", "Maten Soranaki"], "img": "Maten_Overseer.png" },
  { "name": "Raidenryu", "img": "Raidenryu.png" },
  { "name": "Dark Ananta", aliases: ["Dark Ananta", "Yami Kaira"], "img": "Ananta_Oscuro.png" },
  { "name": "Heavenly Acala", aliases: ["Heavenly Acala", "Fudou Myouou Ten"], "img": "Acala_Celestial.png" },
  { "name": "Acala Exalted", "img": "Acala_Exaltado.png" },
  { "name": "Suzaku", "img": "Suzaku.png" },
  { "name": "Genbu", "img": "Genbu.png" },
  { "name": "Asura", "img": "Asura.png" },
  { "name": "Byakko", "img": "Byakko.png" },
  { "name": "Goemon", "img": "Goemon.png" },
  { "name": "Matsu", "img": "Matsu.png" },
  { "name": "Minamoto", "img": "Minamoto.png" },
  { "name": "Benkei", "img": "Benkei_P.png" },
  { "name": "Kyryn", "img": "Kyryn_C.png" },
  { "name": "Suzaku", "img": "Suzaku_C.png" },
  { "name": "Genbu", "img": "Genbu_C.png" },
  { "name": "Byakko", "img": "Byakko_C.png" },
  { "name": "Souryuu", "img": "Souryuu.png" },
  { "name": "Gunshin Susanoo", aliases: ["Gunshin Susanoo", "Susanoo"], "img": "Gunshin_Susanoo.png" }
];

let score = 0; 
let gameEnded = false; // Evita cambios una vez terminado el juego
const unlockedYoKai = new Set(); // Registro de Yo-kai desbloqueados por índice

// Normalizar la entrada del usuario (sin tildes y en minúsculas)
function normalizeString(str) {
    return str.normalize("NFD").replace(/[̀-\u036f]/g, "").toLowerCase();
}

// Crear el objeto de audio una sola vez
let getSound = new Audio("get.mp3");

// Reproducir sonido cuando se desbloquea un Yo-kai (sin solapamiento)
function playGetSound() {
    if (!getSound.paused) {
        getSound.pause(); // Detener el sonido actual si ya está reproduciéndose
        getSound.currentTime = 0; // Reiniciar el sonido al principio
    }
    getSound.play(); // Reproducir el sonido
}

// Actualizar la puntuación en formato (adivinados / totales)
function updateScoreDisplay() {
    const scoreDisplay = document.getElementById("score");
    scoreDisplay.textContent = `${score}/${yoKaiList.length}`;
}

// Verificar la respuesta del usuario
function checkAnswer() {
    if (gameEnded) return; // Si el juego ha terminado, no hacer nada

    const userAnswer = normalizeString(document.getElementById("answer-input").value.trim());

    let correctGuess = false; // Bandera para reproducir el sonido solo si hay aciertos

    yoKaiList.forEach((yoKai, index) => {
        // Normaliza todos los nombres asociados al Yo-kai
        const normalizedNames = [yoKai.name, ...(yoKai.aliases || [])].map(name => normalizeString(name));

        // Si la respuesta coincide con alguno de los nombres y no ha sido desbloqueado
        if (normalizedNames.includes(userAnswer) && !unlockedYoKai.has(index)) {
            const yoKaiImg = document.getElementById(`yo-kai${index + 1}`);
            if (yoKaiImg && yoKaiImg.src.includes("no-kai.png")) {
                yoKaiImg.src = yoKai.img; // Actualiza la imagen

                // Añadir clase para animación
                yoKaiImg.classList.add("yokai-unlocked");
                yoKaiImg.addEventListener("animationend", () => {
                    yoKaiImg.classList.remove("yokai-unlocked"); // Quitar clase tras animación
                });

                unlockedYoKai.add(index); // Marcar el Yo-kai como desbloqueado
                score++;
                correctGuess = true; // Se encontró un acierto
            }
        }
    });

    if (correctGuess) {
        playGetSound(); // Reproducir sonido solo si hubo un acierto
        updateScoreDisplay(); // Actualizar puntuación
        document.getElementById("answer-input").value = ""; // Borra la respuesta después de un acierto
    }

    checkGameEnd(); // Verifica si el juego ha terminado
}

// Verificar si el juego ha terminado (cuando se han adivinado todos los Yo-kai)
function checkGameEnd() {
    if (score === yoKaiList.length) {
        gameEnded = true;
        stopTimer(); // Detener el temporizador
        showCongratsImage(); // Mostrar imagen de "¡Felicidades!"
    }
}

function showCongratsImage() {

    // Detener temporizador
    stopTimer();

    // Obtener tiempo final mostrado
    const tiempoTotal = document.getElementById("time").textContent;

    // Sonido de victoria
    const victorySound = new Audio("congrats.mp3");
    victorySound.volume = 0.8;
    victorySound.play().catch(() => {});

    // Panel lateral
    const finalPanel = document.createElement("div");
    finalPanel.style.position = "fixed";
    finalPanel.style.top = "0";
    finalPanel.style.right = "-350px";
    finalPanel.style.width = "320px";
    finalPanel.style.height = "100%";
    finalPanel.style.backgroundColor = "#0b2a4a";
    finalPanel.style.color = "white";
    finalPanel.style.padding = "20px";
    finalPanel.style.boxSizing = "border-box";
    finalPanel.style.zIndex = "1000";
    finalPanel.style.fontFamily = "Arial, sans-serif";
    finalPanel.style.display = "flex";
    finalPanel.style.flexDirection = "column";
    finalPanel.style.transition = "right 0.6s ease";

    // Botón cerrar
    const closeBtn = document.createElement("div");
    closeBtn.textContent = "✖";
    closeBtn.style.position = "absolute";
    closeBtn.style.top = "15px";
    closeBtn.style.right = "15px";
    closeBtn.style.cursor = "pointer";
    closeBtn.style.fontSize = "18px";

    closeBtn.addEventListener("click", () => {
        finalPanel.style.right = "-350px";
        setTimeout(() => finalPanel.remove(), 600);
    });

    // Título
    const title = document.createElement("h2");
    title.textContent = `Congrats! You've guessed all the Yo-kai in ${tiempoTotal}`;
    title.style.marginTop = "40px";
    title.style.marginBottom = "30px";
    title.style.fontSize = "22px";

    // Texto Twitter
    const followText = document.createElement("p");
    followText.innerHTML = `
        If you liked it, why not follow me on twitter?: 
        <a href="https://x.com/salty_baconV2" target="_blank" style="color:#4fc3ff; text-decoration:none;">
        @Salty_BaconV2
        </a>
    `;
    followText.style.fontSize = "16px";
    followText.style.marginTop = "auto";

    // Montaje
    finalPanel.appendChild(closeBtn);
    finalPanel.appendChild(title);
    finalPanel.appendChild(followText);
    document.body.appendChild(finalPanel);

    // Animación de entrada
    setTimeout(() => {
        finalPanel.style.right = "0";
    }, 50);
}

    // Ocultar la imagen al hacer clic
    congratsImg.addEventListener("click", () => {
        congratsImg.remove();
    });

    document.body.appendChild(congratsImg);
}

// Temporizador
let startTime;
let timerInterval;

function startTimer() {
    startTime = Date.now();
    timerInterval = setInterval(updateTimer, 1000);
}

function updateTimer() {
    const currentTime = Date.now();
    const elapsedTime = currentTime - startTime;

    const hours = Math.floor(elapsedTime / (1000 * 60 * 60));
    const minutes = Math.floor((elapsedTime % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((elapsedTime % (1000 * 60)) / 1000);

    const formattedTime = `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
    document.getElementById("time").textContent = formattedTime;
}

function stopTimer() {
    clearInterval(timerInterval);
}

// Manejador de evento: validación automática con "input"
document.getElementById("answer-input").addEventListener("input", checkAnswer);

// Inicializar el marcador y temporizador al cargar la página
updateScoreDisplay(); // Inicializa la puntuación en 0/total
startTimer();

window.addEventListener("beforeunload", (event) => {
    if (score > 0) { // Mostrar advertencia solo si hay progreso
        event.preventDefault();
        event.returnValue = "¿Estás seguro de que quieres salir? Se perderá todo el progreso.";
    }
});
